In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
from pathlib import Path
import pandas as pd
import numpy as np

project_path = Path.home() / "Documents" / "17th_Lok_Sabha_Analysis"
data_path = project_path / "data" / "processed" / "17th_cleaned.csv"

df = pd.read_csv(data_path)

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (559, 97)

,Name,Constituency,Minister,Attendance,Debates,Questions,Private Member Bills,State,Party,Nature of membership,...,Debates (Clarification On The Statement By Minister),Debates (Felicitations),Questions (Consumer Affairs),Questions (Micro),Debates (Ls - Half-An-Hour Discussions (Rule-55)),Questions (Atomic Energy),Questions (Heavy Industries),Questions (Space),"Questions (Personnel, Public Grievances And Pensions)",End of Term Date
0,Abdul Khaleque,Barpeta,No,92.00%,68,279,8,Assam,Indian National Congress,Elected,...,0,0,0,0,0,0,0,0,0,NaN
1,Abhishek Banerjee,Diamond Harbour,No,19.80%,2,84,0,West Bengal,All India Trinamool Congress,Elected,...,0,0,0,0,0,0,0,0,0,NaN
2,Abu Hasem Khan Choudhury,Maldaha Dakshin,No,55.93%,5,12,0,West Bengal,Indian National Congress,Elected,...,0,0,0,0,0,0,0,0,0,NaN
3,Abu Taher Khan,Murshidabad,No,63.07%,6,4,0,West Bengal,All India Trinamool Congress,Elected,...,0,0,0,0,0,0,0,0,0,NaN
4,Achyutananda Samanta,Kandhamal,No,65.47%,33,169,0,Odisha,Biju Janata Dal,Elected,...,0,0,0,0,0,0,0,0,0,NaN

In [3]:
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Duplicate rows:", df.duplicated().sum())

Rows: 559
Columns: 97
Duplicate rows: 0

In [4]:
print("Data types:")
display(df.dtypes.value_counts())

print("\nMissing values in important columns:")
display(
    df[
        [
            "Name",
            "Constituency",
            "Minister",
            "Attendance",
            "Debates",
            "Questions",
            "Private Member Bills",
            "Party",
            "State"
        ]
    ].isnull().sum()
)

print("\nAttendance data type:", df["Attendance"].dtype)
print("Sample attendance values:", df["Attendance"].head().tolist())

Data types:

int64      81
str        15
float64     1
Name: count, dtype: int64

Missing values in important columns:

Name                     0
Constituency             0
Minister                 0
Attendance              34
Debates                  0
Questions                0
Private Member Bills     0
Party                    0
State                    0
dtype: int64

Attendance data type: str
Sample attendance values: ['92.00%', '19.80%', '55.93%', '63.07%', '65.47%']

In [5]:
# Keep the original values, but create a numeric attendance column
df["Attendance_pct"] = pd.to_numeric(
    df["Attendance"]
        .str.replace("%", "", regex=False),
    errors="coerce"
)

print("Attendance data type:", df["Attendance_pct"].dtype)
print("Missing attendance values:", df["Attendance_pct"].isna().sum())

display(
    df[["Name", "Attendance", "Attendance_pct"]].head()
)

Attendance data type: float64
Missing attendance values: 34

                       Name Attendance  Attendance_pct
0            Abdul Khaleque     92.00%           92.00
1         Abhishek Banerjee     19.80%           19.80
2  Abu Hasem Khan Choudhury     55.93%           55.93
3            Abu Taher Khan     63.07%           63.07
4      Achyutananda Samanta     65.47%           65.47

In [6]:
display(df["Attendance_pct"].describe())

count    525.000000
mean      79.167010
std       17.264025
min        0.000000
25%       71.670000
50%       83.270000
75%       91.200000
max      100.000000
Name: Attendance_pct, dtype: float64

In [7]:
def find_mp(name):
    name = name.strip()

    if not name:
        print("Enter an MP's name.")
        return

    matches = df[
        df["Name"].str.contains(
            name,
            case=False,
            na=False,
            regex=False
        )
    ]

    if matches.empty:
        print(f"No MP found matching '{name}'.")
        return

    columns = [
        "Name",
        "Constituency",
        "Party",
        "State",
        "Minister",
        "Attendance",
        "Debates",
        "Questions",
        "Private Member Bills"
    ]

    display(matches[columns].reset_index(drop=True))

In [8]:
find_mp("Abhishek Banerjee")
find_mp("Khaleque")
find_mp("rahul")
find_mp("nonexistentperson")

,Name,Constituency,Party,State,Minister,Attendance,Debates,Questions,Private Member Bills
0,Abhishek Banerjee,Diamond Harbour,All India Trinamool Congress,West Bengal,No,19.80%,2,84,0

,Name,Constituency,Party,State,Minister,Attendance,Debates,Questions,Private Member Bills
0,Abdul Khaleque,Barpeta,Indian National Congress,Assam,No,92.00%,68,279,8

,Name,Constituency,Party,State,Minister,Attendance,Debates,Questions,Private Member Bills
0,Rahul Gandhi,Wayanad,Indian National Congress,Kerala,No,50.53%,8,99,0
1,Rahul Kaswan,Churu,Bharatiya Janata Party,Rajasthan,No,96.13%,98,277,3
2,Rahul Ramesh Shewale,Mumbai-South-Central,Shiv Sena,Maharashtra,No,95.07%,143,531,13

No MP found matching 'nonexistentperson'.

In [9]:
def filter_mps(state=None, party=None, minister=None):
    results = df.copy()

    if state:
        results = results[
            results["State"].str.contains(
                state, case=False, na=False, regex=False
            )
        ]

    if party:
        results = results[
            results["Party"].str.contains(
                party, case=False, na=False, regex=False
            )
        ]

    if minister is not None:
        results = results[
            results["Minister"].str.casefold() == minister.casefold()
        ]

    columns = [
        "Name", "Constituency", "Party", "State",
        "Minister", "Attendance", "Debates",
        "Questions", "Private Member Bills"
    ]

    display(results[columns].reset_index(drop=True))
    print(f"Matching MPs: {len(results)}")

In [10]:
filter_mps(state="Tamil Nadu")
filter_mps(party="Indian National Congress")
filter_mps(minister="Yes")
filter_mps(state="Tamil Nadu", minister="No")

,Name,Constituency,Party,State,Minister,Attendance,Debates,Questions,Private Member Bills
0,A.K.P. Chinraj,Namakkal,Dravida Munnetra Kazhagam,Tamil Nadu,No,74.07%,12,263,0
1,Andimuthu Raja,Nilgiris,Dravida Munnetra Kazhagam,Tamil Nadu,No,74.07%,43,271,2
2,A. Chellakumar,Krishnagiri,Indian National Congress,Tamil Nadu,No,66.00%,27,195,0
3,C.N. Annadurai,Tiruvannamalai,Dravida Munnetra Kazhagam,Tamil Nadu,No,80.33%,55,451,1
4,D. Ravikumar,Viluppuram,Dravida Munnetra Kazhagam,Tamil Nadu,No,68.00%,60,220,5
5,Dayanidhi Maran,Chennai Central,Dravida Munnetra Kazhagam,Tamil Nadu,No,75.73%,20,136,0
6,Dhanush M Kumar,Tenkasi,Dravida Munnetra Kazhagam,Tamil Nadu,No,98.80%,121,490,2
7,D.M. Kathir Anand,Vellore,Dravida Munnetra Kazhagam,Tamil Nadu,No,67.36%,32,262,5
8,DNV Senthilkumar S.,Dharmapuri,Dravida Munnetra Kazhagam,Tamil Nadu,No,98.80%,316,511,6
9,G. Selvam,Kancheepuram,Dravida Munnetra Kazhagam,Tamil Nadu,No,82.00%,18,436,1
10,A. Ganeshamurthi,Erode,Dravida Munnetra Kazhagam,Tamil Nadu,No,68.93%,30,276,1
11,Gautham Sigamani Pon,Kallakurichi,Dravida Munnetra Kazhagam,Tamil Nadu,No,91.40%,53,379,2
12,H. Vasanthakumar,Kanniyakumari,Indian National Congress,Tamil Nadu,No,86.67%,40,104,2
13,K. Jayakumar,Tiruvallur,Indian National Congress,Tamil Nadu,No,88.53%,33,38,0
14,K. Navaskani,Ramanathapuram,Indian Union Muslim League,Tamil Nadu,No,91.20%,134,271,3
15,K. Shanmugasundaram,Pollachi,Dravida Munnetra Kazhagam,Tamil Nadu,No,69.67%,19,216,0
16,K. Subbarayan,Tiruppur,Communist Party of India,Tamil Nadu,No,61.67%,58,169,0
17,Kanimozhi Karunanidhi,Thoothukkudi,Dravida Munnetra Kazhagam,Tamil Nadu,No,68.73%,65,182,2
18,Karti P. Chidambaram,Sivaganga,Indian National Congress,Tamil Nadu,No,80.87%,24,165,2
19,M. Selvaraj,Nagapattinam,Communist Party of India,Tamil Nadu,No,45.47%,57,239,0
20,Manicka Tagore,Virudhunagar,Indian National Congress,Tamil Nadu,No,88.47%,96,317,0
21,M.K. Vishnu Prasad,Arani,Indian National Congress,Tamil Nadu,No,78.60%,29,254,2
22,P. Raveendranath Kumar,Theni,All India Anna Dravida Munnetra Kazhagam,Tamil Nadu,No,54.67%,103,196,0
23,P. Velusamy,Dindigul,Dravida Munnetra Kazhagam,Tamil Nadu,No,81.73%,16,211,0
24,P.R. Natarajan,Coimbatore,Communist Party of India (Marxist),Tamil Nadu,No,87.07%,56,253,0
25,S. Gnanathiraviam,Tirunelveli,Dravida Munnetra Kazhagam,Tamil Nadu,No,63.93%,25,251,0
26,S. Jagathrakshakan,Arakkonam,Dravida Munnetra Kazhagam,Tamil Nadu,No,38.60%,18,272,0
27,S. Jothimani,Karur,Indian National Congress,Tamil Nadu,No,75.07%,42,201,2
28,S. Ramalingam,Mayiladuthurai,Dravida Munnetra Kazhagam,Tamil Nadu,No,72.07%,16,148,0
29,S. Venkatesan,Madurai,Communist Party of India (Marxist),Tamil Nadu,No,77.60%,33,256,0
30,S.R. Parthiban,Salem,Dravida Munnetra Kazhagam,Tamil Nadu,No,89.40%,42,286,0
31,S.S. Palanimanickam,Thanjavur,Dravida Munnetra Kazhagam,Tamil Nadu,No,54.20%,7,0,0
32,Su Thirunavukkarasar,Tiruchirappalli,Indian National Congress,Tamil Nadu,No,69.60%,37,358,2
33,Sumathy Thamizhachi Thangapandian,Chennai South,Dravida Munnetra Kazhagam,Tamil Nadu,No,78.87%,63,292,8
34,Thalikkottai Rajuthevar Baalu,Sriperumbudur,Dravida Munnetra Kazhagam,Tamil Nadu,No,84.87%,58,225,0
35,Thirumaa Valavan Thol,Chidambaram,Viduthalai Chiruthaigal Katchi,Tamil Nadu,No,66.13%,69,157,6
36,T.R. Paarivendhar,Perambalur,Dravida Munnetra Kazhagam,Tamil Nadu,No,56.47%,40,268,2
37,T.R.V.S. Ramesh,Cuddalore,Dravida Munnetra Kazhagam,Tamil Nadu,No,34.53%,5,183,0
38,V. Kalanidhi,Chennai North,Dravida Munnetra Kazhagam,Tamil Nadu,No,83.87%,59,295,3
39,Vijayakumar alias Vijay Vasanth,Kanniyakumari,Indian National Congress,Tamil Nadu,No,90.10%,21,194,0

Matching MPs: 40

,Name,Constituency,Party,State,Minister,Attendance,Debates,Questions,Private Member Bills
0,Abdul Khaleque,Barpeta,Indian National Congress,Assam,No,92.00%,68,279,8
1,Abu Hasem Khan Choudhury,Maldaha Dakshin,Indian National Congress,West Bengal,No,55.93%,5,12,0
2,Adhir Ranjan Chowdhury,Baharampur,Indian National Congress,West Bengal,No,89.33%,233,69,5
3,Adoor Prakash,Attingal,Indian National Congress,Kerala,No,82.87%,66,388,0
4,Amar Singh,Fatehgarh Sahib,Indian National Congress,Punjab,No,86.33%,56,217,0
5,Anto Antony,Pathanamthitta,Indian National Congress,Kerala,No,82.40%,61,386,2
6,Anumula Revanth Reddy,Malkajgiri,Indian National Congress,Telangana,No,67.07%,17,197,0
7,Balubhau Dhannorkar,Chandrapur,Indian National Congress,Maharashtra,No,67.27%,37,281,0
8,Benny Behanan,Chalakudy,Indian National Congress,Kerala,No,85.13%,69,343,3
9,A. Chellakumar,Krishnagiri,Indian National Congress,Tamil Nadu,No,66.00%,27,195,0
10,Dean Kuriakose,Idukki,Indian National Congress,Kerala,No,90.33%,91,289,12
11,Deepak Baij,Bastar,Indian National Congress,Chhattisgarh,No,81.00%,37,301,0
12,D.K. Suresh,Bangalore Rural,Indian National Congress,Karnataka,No,72.13%,21,395,0
13,Francisco Sardinha,South Goa,Indian National Congress,Goa,No,94.67%,14,87,0
14,Geeta Kora,Singhbhum,Indian National Congress,Jharkhand,No,73.20%,14,279,0
15,Gourav Gogoi,Kaliabor,Indian National Congress,Assam,No,76.33%,78,245,5
16,Gurjeet Singh Aujla,Amritsar,Indian National Congress,Punjab,No,86.67%,45,110,0
17,H. Vasanthakumar,Kanniyakumari,Indian National Congress,Tamil Nadu,No,86.67%,40,104,2
18,Hibi Eden,Ernakulam,Indian National Congress,Kerala,No,91.00%,61,318,9
19,Jasbir Singh,Khadoor Sahib,Indian National Congress,Punjab,No,94.47%,75,102,2
20,Jyotsna Charandas Mahant,Korba,Indian National Congress,Chhattisgarh,No,68.33%,7,116,0
21,K. Jayakumar,Tiruvallur,Indian National Congress,Tamil Nadu,No,88.53%,33,38,0
22,K. Muraleedharan,Vadakara,Indian National Congress,Kerala,No,90.67%,61,266,0
23,Karti P. Chidambaram,Sivaganga,Indian National Congress,Tamil Nadu,No,80.87%,24,165,2
24,Komati Reddy Venkat Reddy,Bhongir,Indian National Congress,Telangana,No,56.00%,22,357,0
25,Kuldeep Rai Sharma,Andaman and Nicobar Islands,Indian National Congress,Andaman and Nicobar Islands,No,73.40%,834,610,9
26,Kumbakudi Sudhakaran,Kannur,Indian National Congress,Kerala,No,51.47%,19,275,0
27,M. K. Raghavan,Kozhikode,Indian National Congress,Kerala,No,81.33%,54,270,11
28,Manicka Tagore,Virudhunagar,Indian National Congress,Tamil Nadu,No,88.47%,96,317,0
29,Manish Tewari,Anandpur Sahib,Indian National Congress,Punjab,No,95.67%,79,212,6
30,M.K. Vishnu Prasad,Arani,Indian National Congress,Tamil Nadu,No,78.60%,29,254,2
31,Mohammad Jawed,Kishanganj,Indian National Congress,Bihar,No,95.87%,53,229,6
32,Mohammad Sadique,Faridkot,Indian National Congress,Punjab,No,65.67%,14,2,0
33,Nakul Nath,Chhindwara,Indian National Congress,Madhya Pradesh,No,71.13%,1,30,0
34,Pradyut Bordoloi,Nawgong,Indian National Congress,Assam,No,82.07%,31,256,3
35,Pratibha Singh,Mandi,Indian National Congress,Himachal Pradesh,No,64.89%,2,29,0
36,Preneet Kaur,Patiala,Indian National Congress,Punjab,No,83.53%,18,27,0
37,Rahul Gandhi,Wayanad,Indian National Congress,Kerala,No,50.53%,8,99,0
38,Rajmohan Unnithan,Kasaragod,Indian National Congress,Kerala,No,86.07%,52,208,0
39,Ramya Haridas,Alathur,Indian National Congress,Kerala,No,74.33%,54,321,0
40,Ravneet Singh,Ludhiana,Indian National Congress,Punjab,No,90.40%,56,367,5
41,S. Jothimani,Karur,Indian National Congress,Tamil Nadu,No,75.07%,42,201,2
42,Santokh Singh Chaudhary,Jalandhar,Indian National Congress,Punjab,No,82.20%,19,45,2
43,Saptagiri Sankar Ulaka,Koraput,Indian National Congress,Odisha,No,90.93%,124,240,2
44,Shashi Tharoor,Thiruvananthapuram,Indian National Congress,Kerala,No,93.13%,101,275,13
45,Sonia Gandhi,Rae Bareli,Indian National Congress,Uttar Pradesh,No,47.20%,6,0,0
46,Su Thirunavukkarasar,Tiruchirappalli,Indian National Congress,Tamil Nadu,No,69.60%,37,358,2
47,Suresh Kodikunnil,Mavelikkara,Indian National Congress,Kerala,No,86.33%,124,304,8
48,T.N. Prathapan,Thrissur,Indian National Congress,Kerala,No,82.20%,67,312,1
49,Uttam Kumar Nalamada Reddy,Nalgonda,Indian National Congress,Telangana,No,84.14%,18,187,0
50,Ve. Vaithilingam,Puducherry,Indian National Congress,Puducherry,No,73.33%,28,63,0
51,Vijayakumar alias Vijay Vasanth,Kanniyakumari,Indian National Congress,Tamil Nadu,No,90.10%,21,194,0
52,Vincent H Pala,Shillong,Indian National Congress,Meghalaya,No,79.07%,17,235,2
53,V.K. Sreekandan,Palakkad,Indian National Congress,Kerala,No,92.87%,63,294,9

Matching MPs: 54

,Name,Constituency,Party,State,Minister,Attendance,Debates,Questions,Private Member Bills
0,Ajay Bhatt,Nainital-Udhamsingh Nagar,Bharatiya Janata Party,Uttarakhand,Yes,98.60%,48,45,3
1,Ajay Misra Teni,Kheri,Bharatiya Janata Party,Uttar Pradesh,Yes,94.40%,56,160,4
2,Amit Anil Chandra Shah,Gandhinagar,Bharatiya Janata Party,Gujarat,Yes,NaN,0,0,0
3,Annpurna Devi,Kodarma,Bharatiya Janata Party,Jharkhand,Yes,77.60%,31,97,0
4,Anupriya Singh Patel,Mirzapur,Apna Dal,Uttar Pradesh,Yes,96.60%,44,9,0
...,...,...,...,...,...,...,...,...,...
66,S.P. Singh Baghel,Agra,Bharatiya Janata Party,Uttar Pradesh,Yes,93.40%,23,5,0
67,Subhas Sarkar,Bankura,Bharatiya Janata Party,West Bengal,Yes,82.60%,27,52,0
68,Suresh Channabasappa Angadi,Belgaum,Bharatiya Janata Party,Karnataka,Yes,NaN,0,0,0
69,Vijay Kumar Singh,Ghaziabad,Bharatiya Janata Party,Uttar Pradesh,Yes,NaN,0,0,0
70,Virendra Kumar,Tikamgarh,Bharatiya Janata Party,Madhya Pradesh,Yes,97.40%,41,81,0

Matching MPs: 71

,Name,Constituency,Party,State,Minister,Attendance,Debates,Questions,Private Member Bills
0,A.K.P. Chinraj,Namakkal,Dravida Munnetra Kazhagam,Tamil Nadu,No,74.07%,12,263,0
1,Andimuthu Raja,Nilgiris,Dravida Munnetra Kazhagam,Tamil Nadu,No,74.07%,43,271,2
2,A. Chellakumar,Krishnagiri,Indian National Congress,Tamil Nadu,No,66.00%,27,195,0
3,C.N. Annadurai,Tiruvannamalai,Dravida Munnetra Kazhagam,Tamil Nadu,No,80.33%,55,451,1
4,D. Ravikumar,Viluppuram,Dravida Munnetra Kazhagam,Tamil Nadu,No,68.00%,60,220,5
5,Dayanidhi Maran,Chennai Central,Dravida Munnetra Kazhagam,Tamil Nadu,No,75.73%,20,136,0
6,Dhanush M Kumar,Tenkasi,Dravida Munnetra Kazhagam,Tamil Nadu,No,98.80%,121,490,2
7,D.M. Kathir Anand,Vellore,Dravida Munnetra Kazhagam,Tamil Nadu,No,67.36%,32,262,5
8,DNV Senthilkumar S.,Dharmapuri,Dravida Munnetra Kazhagam,Tamil Nadu,No,98.80%,316,511,6
9,G. Selvam,Kancheepuram,Dravida Munnetra Kazhagam,Tamil Nadu,No,82.00%,18,436,1
10,A. Ganeshamurthi,Erode,Dravida Munnetra Kazhagam,Tamil Nadu,No,68.93%,30,276,1
11,Gautham Sigamani Pon,Kallakurichi,Dravida Munnetra Kazhagam,Tamil Nadu,No,91.40%,53,379,2
12,H. Vasanthakumar,Kanniyakumari,Indian National Congress,Tamil Nadu,No,86.67%,40,104,2
13,K. Jayakumar,Tiruvallur,Indian National Congress,Tamil Nadu,No,88.53%,33,38,0
14,K. Navaskani,Ramanathapuram,Indian Union Muslim League,Tamil Nadu,No,91.20%,134,271,3
15,K. Shanmugasundaram,Pollachi,Dravida Munnetra Kazhagam,Tamil Nadu,No,69.67%,19,216,0
16,K. Subbarayan,Tiruppur,Communist Party of India,Tamil Nadu,No,61.67%,58,169,0
17,Kanimozhi Karunanidhi,Thoothukkudi,Dravida Munnetra Kazhagam,Tamil Nadu,No,68.73%,65,182,2
18,Karti P. Chidambaram,Sivaganga,Indian National Congress,Tamil Nadu,No,80.87%,24,165,2
19,M. Selvaraj,Nagapattinam,Communist Party of India,Tamil Nadu,No,45.47%,57,239,0
20,Manicka Tagore,Virudhunagar,Indian National Congress,Tamil Nadu,No,88.47%,96,317,0
21,M.K. Vishnu Prasad,Arani,Indian National Congress,Tamil Nadu,No,78.60%,29,254,2
22,P. Raveendranath Kumar,Theni,All India Anna Dravida Munnetra Kazhagam,Tamil Nadu,No,54.67%,103,196,0
23,P. Velusamy,Dindigul,Dravida Munnetra Kazhagam,Tamil Nadu,No,81.73%,16,211,0
24,P.R. Natarajan,Coimbatore,Communist Party of India (Marxist),Tamil Nadu,No,87.07%,56,253,0
25,S. Gnanathiraviam,Tirunelveli,Dravida Munnetra Kazhagam,Tamil Nadu,No,63.93%,25,251,0
26,S. Jagathrakshakan,Arakkonam,Dravida Munnetra Kazhagam,Tamil Nadu,No,38.60%,18,272,0
27,S. Jothimani,Karur,Indian National Congress,Tamil Nadu,No,75.07%,42,201,2
28,S. Ramalingam,Mayiladuthurai,Dravida Munnetra Kazhagam,Tamil Nadu,No,72.07%,16,148,0
29,S. Venkatesan,Madurai,Communist Party of India (Marxist),Tamil Nadu,No,77.60%,33,256,0
30,S.R. Parthiban,Salem,Dravida Munnetra Kazhagam,Tamil Nadu,No,89.40%,42,286,0
31,S.S. Palanimanickam,Thanjavur,Dravida Munnetra Kazhagam,Tamil Nadu,No,54.20%,7,0,0
32,Su Thirunavukkarasar,Tiruchirappalli,Indian National Congress,Tamil Nadu,No,69.60%,37,358,2
33,Sumathy Thamizhachi Thangapandian,Chennai South,Dravida Munnetra Kazhagam,Tamil Nadu,No,78.87%,63,292,8
34,Thalikkottai Rajuthevar Baalu,Sriperumbudur,Dravida Munnetra Kazhagam,Tamil Nadu,No,84.87%,58,225,0
35,Thirumaa Valavan Thol,Chidambaram,Viduthalai Chiruthaigal Katchi,Tamil Nadu,No,66.13%,69,157,6
36,T.R. Paarivendhar,Perambalur,Dravida Munnetra Kazhagam,Tamil Nadu,No,56.47%,40,268,2
37,T.R.V.S. Ramesh,Cuddalore,Dravida Munnetra Kazhagam,Tamil Nadu,No,34.53%,5,183,0
38,V. Kalanidhi,Chennai North,Dravida Munnetra Kazhagam,Tamil Nadu,No,83.87%,59,295,3
39,Vijayakumar alias Vijay Vasanth,Kanniyakumari,Indian National Congress,Tamil Nadu,No,90.10%,21,194,0

Matching MPs: 40

In [11]:
%pip install pymupdf

Requirement already satisfied: pymupdf in C:\Users\Tony\anaconda3\Lib\site-packages (1.28.2)
Note: you may need to restart the kernel to use updated packages.

In [12]:
from pathlib import Path
import fitz  # PyMuPDF

pdf_path = Path("data/raw/Floor.pdf")

doc = fitz.open(pdf_path)

print("Total pages:", len(doc))
print("Page 60 preview:")
print(doc[59].get_text()[:2000])

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.
Total pages: 89
Page 60 preview:
31.01.2024

58

Honorable Members,
This is my first address in this new Parliament building. This magnificent
building has been constructed at the beginning of “Azadi ka Amrit Kaal”. It is
imbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to
India’s civilization and culture. It also resonates with the resolve to respect our
democratic and parliamentary traditions. Moreover, it embodies the commitment
to forge new traditions for the new India of the 21st century. I am confident that
this new building will be witness to productive dialogue on policies -- policies that
will shape the development of ‘Viksit Bharat’ in the Amrit Kaal of our
independence. I extend my best wishes to all of you.
Honorable Members, this year is also the 75th year of adoption of our
Constitution. During this period, Amrit Mahotsav, the celebration of 75 years
of independence, was completed. During this period, many programmes were
organized across the country. The country remembered its unsung freedom
fighters. After 75 years, the young generation relived that period of
freedom struggle.
During this campaign Amrit Kalash containing soil from every village of the
country were brought to Delhi under the ‘Meri Maati, Mera Desh’ campaign. Over
2 lakh plaques were installed.  More than three crore people took the oath of the
‘Panch Pran’.  More than 70,000 Amrit Sarovars were built. Construction of more
than two lakh “Amrit Vatikas” was completed. Over two crore trees were planted.
More than 16 crore people uploaded their selfies with the Tricolour.

In [13]:
import pymupdf

doc = pymupdf.open(pdf_path)

for page_num in range(82, 89):
    print(f"\n{'=' * 20} PDF PAGE {page_num + 1} {'=' * 20}\n")
    print(doc[page_num].get_text()[:1200])

==================== PDF PAGE 83 ====================

31.01.2024

81

industry. In the last 10 years, India has successfully organized international sports
events related to many sports. ‘Mera Yuva Bharat’ Organization has been formed
to motivate our youth to contribute for building a ‘Viksit Bharat’ and to instill
among them a sense of duty and spirit of service. So far, about 1 crore youth
have joined this initiative.
Honorable Members, we have seen the advantage of having a strong
government during a period of upheaval. The world has been in a turmoil in the
last 3 years. There are many conflicts raging in different parts of the world. My
government has established India as a Vishwa-Mitra in these difficult times. It is
because of India’s role as Vishwa-Mitra that we  have become the voice of the
Global South today. In the last 10 years, another conventional way of thinking has
been changed. Earlier, events related to diplomacy were confined to the corridors
of Delhi. My government has ensured direct participation of  the public in this
also. We saw a great example of this during India’s G-20 presidency. The way
India connected the G-20 with the public was unprecedented. The world was
introduced to the real poten

==================== PDF PAGE 84 ====================

31.01.2024

82

- Middle East - Europe Corridor was announced. This corridor will further
strengthen India’s maritime capability. The launch of the Global Biofuel Alliance is
also a big event. Such steps are expanding India’s role in solving
global problems.
Honorable Members, even in this era of global disputes and conflicts, my
government has firmly placed India’s interests before the world. The scope of
India’s foreign policy today has gone far beyond the constraints of the
past. Today India is a respected member of many global organizations. Today
India is a leading voice in the world against terrorism.  Today India responds
strongly and takes initiatives for the humanity caught in crises. Wherever there is
a crisis in the world today, India tries to respond promptly. My government has
instilled new confidence in Indians working across the world. Wherever
crisis occurred, we have evacuated every Indian safely through campaigns like
Operation Ganga, Operation Kaveri, Vande Bharat.
My government has made continuous efforts to propagate the
Indian traditions of Yoga, Pranayam and Ayurveda to the entire world. Last  year,
representatives of 135 countries did yog

==================== PDF PAGE 85 ====================

31.01.2024

83

country witnessed a similar epochal  moment. After waiting for centuries, Ram
Lalla has now been enshrined in his  grand temple in Ayodhya. This was a matter
of aspirations and faith for crores of our  countrymen and the resolution of this
has been accomplished in a  harmonious manner.
Honorable Members, you all represent the aspirations of crores of Indians.
The dreams of  the youth in schools and colleges today are completely different.
It is  the responsibility of all of us to leave no stone unturned to fulfill the  dreams
of the Amrit generation. Viksit Bharat will fulfill the dreams of  our Amrit
generation. For this, we all have to work together to achieve  success in this
endeavour.
Honorable Members, Respected Atal ji had said—
अपनी Åयेय-याýा म¤,
हम कभी Łके नहé ह§।
िकसी चुनौती के सÌमुख
कभी झुके नहé ह§।
My government is moving ahead with the guarantee of fulfilling the  dreams
of 140 crore countrymen. I have full faith that this new Parliament House will
continue to give strength to India’s aspirational journey and create new and
healthy traditions. Many friends will not be in this House to witness the year 2047.





==================== PDF PAGE 86 ====================

31.01.2024

84

But our legacy should be such that the future generations remember us.  Best
wishes to all of you!
Thank you!
Jai Hind!
Jai Bharat!
_______




==================== PDF PAGE 87 ====================

31.01.2024

85

12.58½ hrs
OBITUARY REFERENCES

माननीय अÅय±: माननीय सदÖयगण, मुझे अÂयंत दु:ख के साथ, अपने दो पूवª सािथयŌ के िनधन के
बारे म¤ सभा को सूिचत करना है।

®ी भþेĵर तांती असम के किलयाबोर संसदीय िनवाªचन ±ेý से आठवé लोक सभा के सदÖय
थे।

®ी तांती ने िवशेषािधकार सिमित के सदÖय के łप म¤ कायª िकया।

®ी भþेĵर तांती का िनधन 4 िदसÌबर, 2023 को 79 वषª कì आयु म¤ असम के गोलाघाट म¤
हòआ।

®ी सोनावणे ÿताप नारायणराव महाराÕů के धुले संसदीय िनवाªचन ±ेý से पÆþहवé लोक सभा
के सदÖय थे।

®ी सोनावणे ने जल संसाधन संबंधी सिमित और शहरी िवकास संबंधी सिमित के सदÖय के
łप म¤ कायª िकया।

इससे पूवª, ®ी सोनावणे दो कायªकाल के िलए महाराÕů िवधान पåरषद के सदÖय भी रहे।

®ी सोनावणे ÿताप नारायणराव का िनधन 22 िदसÌबर, 2023 को 75 वषª कì आयु म¤
महाराÕů के नािसक म¤ हòआ।

हम अपने पूवª सािथयŌ के िनधन पर गहरा शोक Óयĉ करते ह§। यह सभा उनके शोकसंतĮ
पåरवारŌ के ÿित अपनी संवेदना Óयĉ करती है।

अब, यह सभा िदवंगत आÂमाओं के सÌमान म¤ कुछ देर के िलए मौन रहेगी।
12.59½ hrs
The Members then stood in silence for a short while.

माननीय अÅय±: ओम् शांित: शांित: शांित:।
________


==================== PDF PAGE 88 ====================

31.01.2024

86

13.00 hrs
COMMITTEE ON PRIVILEGES
7th Report

®ी सुनील कुमार िसंह (चतरा) : माननीय अÅय± महोदय, म§ िवशेषािधकार सिमित का सातवां
ÿितवेदन (िहÆदी और अंúेजी संÖकरण) सभा पटल पर रखता हóं।
________

माननीय अÅय± : सभा कì कायªवाही गुŁवार, 01 फरवरी, 2024 को ÿात: 11 बजे तक के िलए
Öथिगत कì जाती है।
13.01 hrs
The Lok Sabha then adjourned till Eleven of the Clock on
Thursday, February 1, 2024/Magha 12, 1945 (Saka).
________







==================== PDF PAGE 89 ====================

31.01.2024

87





INTERNET
           The Original Version of Lok Sabha proceedings is available on Parliament of India Website and
Lok Sabha Website at the following address:
           www.sansad.in/ls
LIVE TELECAST OF PROCEEDINGS OF LOK SABHA
        Lok Sabha proceedings are being telecast live on Sansad T.V. Channel. Live telecast begins at 11
A.M. everyday the Lok Sabha sits, till the adjournment of the House.

_________________________________________________________________________________
Published under Rules 379 and 382 of the Rules of Procedure and Conduct of Business
 in Lok Sabha (Sixteenth Edition)
_________________________________________________________________________________________________

In [14]:
for page_num in [38, 58, 59, 60, 86]:
    text = doc[page_num].get_text()

    print(f"\n--- PDF PAGE {page_num + 1} ---")
    print(text[:500])

--- PDF PAGE 39 ---
31.01.2024

37

माननीय अÅय±: आइटम नं. 1, महासिचव ।
12.58 hrs
PRESIDENT’S ADDRESS

SECRETARY-GENERAL: I beg to lay on the Table a copy of the President’s
Address to both Houses of Parliament assembled together on the 31st of January,
2024.
माननीय सदÖयगण,
इस नए संसद भवन म¤ यह मेरा पहला संबोधन है। आज़ादी के अमृतकाल कì शुŁआत म¤ यह
भÓय भवन बना है। यहां एक भारत ®ेķ भारत कì महक भी है।भारत कì सËयता और संÖकृित कì
चेतना भी है। इसम¤, हमारी लोकतांिýक और संसदीय परंपराओं के सÌमान का ÿण भी है।स

--- PDF PAGE 59 ---
31.01.2024

57

लेिकन हमारी िवरासत ऐसी होनी चािहए िक तब कì पीढ़ी हम¤ याद करे।
आप सभी को बहòत-बहòत शुभकामनाएं!
धÆयवाद!
जय िहÆद!
जय भारत!





--- PDF PAGE 60 ---
31.01.2024

58

Honorable Members,
This is my first address in this new Parliament building. This magnificent
building has been constructed at the beginning of “Azadi ka Amrit Kaal”. It is
imbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to
India’s civilization and culture. It also resonates with the resolve to respect our
democratic and parliamentary traditions. Moreover, it embodies the commitment
to forge new traditions for the new India of the 21st centu

--- PDF PAGE 61 ---
31.01.2024

59

It was during the Amrit Mahotsav that, A statue of Netaji Subhash Chandra
Bose was installed on “Kartavya Path”. A museum dedicated to all the Prime
Ministers of the country was inaugurated in Delhi, the national capital.
Shantiniketan and Hoysala Temple were included in the World Heritage List. Veer
Bal Diwas was declared in the memory of “Sahibzaade”.  Birth anniversary of
Bhagwan Birsa Munda was declared as “Janjatiya Gaurav Diwas”. August 14 was
declared as “Vibhaja

--- PDF PAGE 87 ---
31.01.2024

85

12.58½ hrs
OBITUARY REFERENCES

माननीय अÅय±: माननीय सदÖयगण, मुझे अÂयंत दु:ख के साथ, अपने दो पूवª सािथयŌ के िनधन के
बारे म¤ सभा को सूिचत करना है।

®ी भþेĵर तांती असम के किलयाबोर संसदीय िनवाªचन ±ेý से आठवé लोक सभा के सदÖय
थे।

®ी तांती ने िवशेषािधकार सिमित के सदÖय के łप म¤ कायª िकया।

®ी भþेĵर तांती का िनधन 4 िदसÌबर, 2023 को 79 वषª कì आयु म¤ असम के गोलाघाट म¤
हòआ।

®ी सोनावणे ÿताप नारायणराव महाराÕů के धुले संसदीय िनवाªचन ±ेý से पÆþहवé लोक सभा
के सदÖय थे।

®ी

In [15]:
for page_num in [38, 58, 59, 60, 86]:
    text = doc[page_num].get_text()

    replacement_chars = text.count("\ufffd")
    mojibake_markers = sum(
        text.count(marker)
        for marker in ["Å", "Ö", "¤", "æ", "ÿ", "þ", "®"]
    )

    print(
        f"PDF page {page_num + 1}: "
        f"{len(text)} characters | "
        f"replacement chars: {replacement_chars} | "
        f"possible mojibake markers: {mojibake_markers}"
    )

PDF page 39: 1634 characters | replacement chars: 0 | possible mojibake markers: 18
PDF page 59: 151 characters | replacement chars: 0 | possible mojibake markers: 1
PDF page 60: 1597 characters | replacement chars: 0 | possible mojibake markers: 0
PDF page 61: 1671 characters | replacement chars: 0 | possible mojibake markers: 0
PDF page 87: 1072 characters | replacement chars: 0 | possible mojibake markers: 29

In [16]:
for page_num in [38, 48, 58]:
    print(f"\n{'=' * 15} PDF PAGE {page_num + 1} {'=' * 15}\n")
    print(doc[page_num].get_text()[:1000])

=============== PDF PAGE 39 ===============

31.01.2024

37

माननीय अÅय±: आइटम नं. 1, महासिचव ।
12.58 hrs
PRESIDENT’S ADDRESS

SECRETARY-GENERAL: I beg to lay on the Table a copy of the President’s
Address to both Houses of Parliament assembled together on the 31st of January,
2024.
माननीय सदÖयगण,
इस नए संसद भवन म¤ यह मेरा पहला संबोधन है। आज़ादी के अमृतकाल कì शुŁआत म¤ यह
भÓय भवन बना है। यहां एक भारत ®ेķ भारत कì महक भी है।भारत कì सËयता और संÖकृित कì
चेतना भी है। इसम¤, हमारी लोकतांिýक और संसदीय परंपराओं के सÌमान का ÿण भी है।साथ ही,
21वé सदी के नए भारत के िलए, नई परंपराओं के िनमाªण का संकÐप भी है।मुझे पूरा िवĵास है िक इस
नए भवन म¤ नीितयŌ पर साथªक संवाद होगा। ऐसी नीितयां जो आज़ादी के अमृतकाल म¤ िवकिसत
भारत का िनमाªण कर¤गी। म§ आप सभी को अपनी शुभकामनाएं देती हóं।
माननीय सदÖयगण, यह हमारे संिवधान के लागू होने का भी 75वां वषª है । इसी कालखंड म¤
आज़ादी के 75 वषª का उÂसव, अमृत महोÂसव भी संपÆन हòआ है । इस दौरान देश भर म¤ अनेक
कायªøम हòए । देश ने अपने गुमनाम Öवतंýता सेनािनयŌ को याद िकया । 75 साल बाद युवा पीढ़ी ने
िफर ÖवतÆý

=============== PDF PAGE 49 ===============

31.01.2024

47

 मÂÖय-पालन ±ेý म¤ 38 हजार करोड़ Łपए से अिधक कì योजनाएं चलाई जा रही है, िजसके
कारण मÂÖय उÂपादन िपछले दस साल म¤ 95 लाख मीिůक टन से बढ़कर 175 लाख मीिůक टन
यानी लगभग दोगुना हो गया है। इनल§ड िफशरीज का उÂपादन 61 लाख मीिůक टन से बढ़कर 131
लाख मीिůक टन हो गया ।  मÂÖय-पालन ±ेý म¤ िनयाªत भी 30 हजार करोड़ Łपए से बढकर 64
हजार करोड़ Łपए तक, यानी दोगुने से ºयादा बढ़ा है। देश म¤ पहली बार पशुपालकŌ और मछुआरŌ को
िकसान øेिडट काडª का लाभ िदया गया है। िपछले दशक म¤, ÿित Óयिĉ दूध उपलÊधता 40 ÿितशत
बढ़ीहै। पशुओं को खुरपका और मुंहपका बीमाåरयŌ से बचाने के िलए पहली बार मुÉत  अब तक, चार
चरणŌ म¤, 50 करोड़ से ºयादा टीके, टीकाकरण अिभयान चल रहा है। पशुओं को िदएजा चुके ह§।
माननीय सदÖयगण, जनकÐयाण कì ये िजतनी भी योजनाएं ह§, ये िसफª सुिवधाएं भर नहé ह§।
इनका देश के नागåरकŌ के पूरे जीवन-चø पर सकाराÂमक असर पड़ रहा है।िविभÆन सरकारी और
गैर-सरकारी संÖथाओं Ĭारा, मेरी सरकार कì योजनाओं के ÿभावŌ का अÅययन िकया गया है। इनके
पåरणाम बहòत ही ÿभावकारी ह§ और गरीबी से लड़ रहे दुिनया के हर देश को ÿेåरत करने वाले ह§। बी

=============== PDF PAGE 59 ===============

31.01.2024

57

लेिकन हमारी िवरासत ऐसी होनी चािहए िक तब कì पीढ़ी हम¤ याद करे।
आप सभी को बहòत-बहòत शुभकामनाएं!
धÆयवाद!
जय िहÆद!
जय भारत!

In [17]:
for page_num in [38, 48, 58, 59, 60, 86]:
    print(f"\n--- PDF PAGE {page_num + 1} ---")
    for font in doc[page_num].get_fonts(full=True):
        print(font)

--- PDF PAGE 39 ---
(11, 'ttf', 'Type0', 'CIDFont+F1', 'F1', 'Identity-H', 0)
(19, 'ttf', 'Type0', 'CIDFont+F2', 'F2', 'Identity-H', 0)
(174, 'ttf', 'Type0', 'CIDFont+F7', 'F3', 'Identity-H', 0)
(182, 'ttf', 'Type0', 'CIDFont+F8', 'F4', 'Identity-H', 0)

--- PDF PAGE 49 ---
(11, 'ttf', 'Type0', 'CIDFont+F1', 'F1', 'Identity-H', 0)

--- PDF PAGE 59 ---
(11, 'ttf', 'Type0', 'CIDFont+F1', 'F1', 'Identity-H', 0)
(160, 'ttf', 'Type0', 'CIDFont+F6', 'F2', 'Identity-H', 0)

--- PDF PAGE 60 ---
(11, 'ttf', 'Type0', 'CIDFont+F1', 'F1', 'Identity-H', 0)

--- PDF PAGE 61 ---
(11, 'ttf', 'Type0', 'CIDFont+F1', 'F1', 'Identity-H', 0)

--- PDF PAGE 87 ---
(11, 'ttf', 'Type0', 'CIDFont+F1', 'F1', 'Identity-H', 0)
(19, 'ttf', 'Type0', 'CIDFont+F2', 'F2', 'Identity-H', 0)
(27, 'ttf', 'Type0', 'CIDFont+F3', 'F3', 'Identity-H', 0)

In [18]:
import pymupdf

page = doc[38]

print("NORMAL EXTRACTION:")
print(page.get_text()[:600])

print("\nRAW DICT EXTRACTION:")
raw = page.get_text("dict")

for block in raw["blocks"]:
    if "lines" in block:
        for line in block["lines"]:
            for span in line["spans"]:
                print(span["text"])

NORMAL EXTRACTION:
31.01.2024

37

माननीय अÅय±: आइटम नं. 1, महासिचव ।
12.58 hrs
PRESIDENT’S ADDRESS

SECRETARY-GENERAL: I beg to lay on the Table a copy of the President’s
Address to both Houses of Parliament assembled together on the 31st of January,
2024.
माननीय सदÖयगण,
इस नए संसद भवन म¤ यह मेरा पहला संबोधन है। आज़ादी के अमृतकाल कì शुŁआत म¤ यह
भÓय भवन बना है। यहां एक भारत ®ेķ भारत कì महक भी है।भारत कì सËयता और संÖकृित कì
चेतना भी है। इसम¤, हमारी लोकतांिýक और संसदीय परंपराओं के सÌमान का ÿण भी है।साथ ही,
21वé सदी के नए भारत के िलए, नई परंपराओं के िनमाªण का संकÐप भी है।मुझे पूरा िवĵास है िक इस
न

RAW DICT EXTRACTION:
31.01.2024

37

माननीय अ
Å
य
±
:
 आइटम नं. 1, महासिचव ।

12.58 hrs
PRESIDENT’S ADDRESS



SECRETARY-GENERAL:
I beg to lay on the Table a copy of the President’s
Address to both Houses of Parliament assembled together on the 31
st
 of January,
2024.


माननीय सद
Ö
यगण,
इस नए संसद भवन म
¤
 यह मेरा पहला संबोधन है। आज़ादी के अमृतकाल क
ì
 शु
Ł
आत म
¤
 यह
भ
Ó
य भवन बना है। यहां एक भारत
®
े
ķ
 भारत क
ì
 महक भी है।भारत क
ì
 स
Ë
यता और सं
Ö
कृित क
ì

चेतना भी है। इसम
¤
, हमारी लोकतांि
ý
क और संसदीय परंपराओं के स
Ì
मान का
ÿ
ण भी है।साथ ही,
21व
é
 सदी के नए भारत के िलए, नई परंपराओं के िनमा
ª
ण का संक
Ð
प भी है।मुझे पूरा िव
ĵ
ास है िक इस
नए भवन म
¤
 नीितय
Ō
 पर साथ
ª
क संवाद होगा। ऐसी नीितयां जो आज़ादी के अमृतकाल म
¤
 िवकिसत
भारत का िनमा
ª
ण कर
¤
गी। म
§
 आप सभी को अपनी शुभकामनाएं देती ह
ó
ं।
माननीय सद
Ö
यगण, यह हमारे संिवधान के लागू होने का भी 75वां वष
ª
 है । इसी कालखंड म
¤

आज़ादी के 75 वष
ª
 का उ
Â
सव, अमृत महो
Â
सव भी संप
Æ
न ह
ò
आ है । इस दौरान देश भर म
¤
 अनेक
काय
ªø
म ह
ò
ए । देश ने अपने गुमनाम
Ö
वतं
ý
ता सेनािनय
Ō
 को याद िकया । 75 साल बाद युवा पीढ़ी ने
िफर
Ö
वत
Æý
ता सं
ú
ाम के उस कालखंड को िजया ।
इस उ
Â
सव के दौरान  मेरी माटी, मेरा देश अिभयान के तहत, देश भर के हर गाँव क
ì
 िम
Ę
ी के
साथ अमृत कलश िद
Ð
ली लाए गए । 2 लाख से
º
यादा िशला-फलकम
Ö
थािपत िकए गए । 3 करोड़ से
º
यादा लोग
Ō
 ने पंच
ÿ
ाण क
ì
 शपथ ली । 70 हजार से
º
यादा अमृत सरोवर बने । 2 लाख से
º
यादा


 Laid on the Table and also placed in Library, See No. LT 11007/17/24.

 Her Excellency Shrimati Droupadi Murmu, President of India, delivered the Address in Lok Sabha Chamber, Parliament
House of India (New building of Parliament) in Hindi, English Text of the Address was read by His Excellency, Shri
Jagdeep Dhankhar, Vice President of India.

In [19]:
for font in doc[38].get_fonts(full=True):
    xref = font[0]
    print(f"\nFont: {font[3]} | xref: {xref}")

    try:
        cmap = doc.extract_font(xref)
        print("Font extraction metadata:", cmap[:3])
    except Exception as e:
        print("Could not extract font:", e)

Font: CIDFont+F1 | xref: 11
Font extraction metadata: ('CIDFont+F1', 'ttf', 'Type0')

Font: CIDFont+F2 | xref: 19
Font extraction metadata: ('CIDFont+F2', 'ttf', 'Type0')

Font: CIDFont+F7 | xref: 174
Font extraction metadata: ('CIDFont+F7', 'ttf', 'Type0')

Font: CIDFont+F8 | xref: 182
Font extraction metadata: ('CIDFont+F8', 'ttf', 'Type0')

In [20]:
%pip install pdfplumber

Requirement already satisfied: pdfplumber in C:\Users\Tony\anaconda3\Lib\site-packages (0.11.10)
Requirement already satisfied: pdfminer.six==20260107 in C:\Users\Tony\anaconda3\Lib\site-packages (from pdfplumber) (20260107)
Requirement already satisfied: Pillow>=12.2.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from pdfplumber) (12.3.0)
Requirement already satisfied: pypdfium2>=5.9.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from pdfplumber) (5.14.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from pdfminer.six==20260107->pdfplumber) (3.4.7)
Requirement already satisfied: cryptography>=36.0.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from pdfminer.six==20260107->pdfplumber) (49.0.0)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.1.0)
Requirement already satisfied: pycparser in C:\Users\Tony\anaconda3\Lib\site-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)
Note: you may need to restart the kernel to use updated packages.

In [21]:
import pdfplumber

with pdfplumber.open(pdf_path) as pdf:
    print("PDF pages:", len(pdf.pages))
    print(pdf.pages[38].extract_text()[:1500])

PDF pages: 89
31.01.2024 37
माननीय अ(cid:197)य(cid:177): आइटम न.ं 1, महासिचव ।
12.58 hrs

PRESIDENT’S ADDRESS
SECRETARY-GENERAL: I beg to lay on the Table a copy of the President’s
Address to both Houses of Parliament assembled together on the 31st of January,
2024.

माननीय सद(cid:214)यगण,
इस नए संसद भवन म(cid:164) यह मेरा पहला संबोधन है। आज़ादी के अमृतकाल क(cid:236) शु(cid:321)आत म (cid:164) यह
भ(cid:211)य भवन बना है। यहां एक भारत (cid:174)े(cid:311) भारत क(cid:236) महक भी है।भारत क(cid:236) स(cid:203)यता और सं(cid:214)कृित क(cid:236)
चेतना भी है। इसम(cid:164), हमारी लोकतांि(cid:253)क और संसदीय परपं राओ ं के स(cid:204)मान का (cid:255)ण भी है।साथ ही,
21व(cid:233) सदी के नए भारत के िलए, नई परपं राओ ंके िनमा(cid:170)ण का संक(cid:208)प भी है।मझु े पूरा िव(cid:309)ास है िक इस
नए भवन म(cid:164) नीितय(cid:332) पर साथ(cid:170)क संवाद होगा। ऐसी नीितयां जो आज़ादी के अमृतकाल म(cid:164) िवकिसत
भारत का िनमा(cid:170)ण करग(cid:164) ी। म(cid:167) आप सभी को अपनी शुभकामनाए ं देती ह(cid:243)ं।
माननीय सद(cid:214)यगण, यह हमार े संिवधान के लागू होने का भी 75वां वष(cid:170) है । इसी कालखंड म (cid:164)
आज़ादी के 75 वष(cid:170) का उ(cid:194)सव, अमतृ महो(cid:194)सव भी सपं (cid:198)न ह(cid:242)आ ह ै । इस दौरान देश भर म(cid:164) अनेक
काय(cid:170)(cid:248)म ह(cid:242)ए । देश ने अपने गमु नाम (cid:214)वतं(cid:253)ता सेनािनय(cid:332) को याद िकया । 75 साल बाद यवु ा पीढ़ी ने
िफर (cid:214)वत(cid:198)(cid:253)ता सं(cid:250)ाम के उस कालखंड को िजया ।
इस उ(cid:194)सव के दौरान मेरी माटी, मेरा देश अिभयान के तहत, देश भर के हर गावँ

In [22]:
import subprocess

result = subprocess.run(
    [r"C:\Program Files\Tesseract-OCR\tesseract.exe", "--list-langs"],
    capture_output=True,
    text=True
)

print(result.stdout)

List of available languages in "C:\Program Files\Tesseract-OCR/tessdata/" (124):
afr
amh
ara
asm
aze
aze_cyrl
bel
ben
bod
bos
bre
bul
cat
ceb
ces
chi_sim
chi_sim_vert
chi_tra
chi_tra_vert
chr
cos
cym
dan
deu
deu_latf
div
dzo
ell
eng
enm
epo
equ
est
eus
fao
fas
fil
fin
fra
frm
fry
gla
gle
glg
grc
guj
hat
heb
hin
hrv
hun
hye
iku
ind
isl
ita
ita_old
jav
jpn
jpn_vert
kan
kat
kat_old
kaz
khm
kir
kmr
kor
lao
lat
lav
lit
ltz
mal
mar
mkd
mlt
mon
mri
msa
mya
nep
nld
nor
oci
ori
osd
pan
pol
por
pus
que
ron
rus
san
sin
slk
slv
snd
spa
spa_old
sqi
srp
srp_latn
sun
swa
swe
syr
tam
tat
tel
tgk
tha
tir
ton
tur
uig
ukr
urd
uzb
uzb_cyrl
vie
yid
yor

In [23]:
import shutil

print(shutil.which("tesseract"))

None

In [24]:
import os
import shutil
import pymupdf

tesseract_dir = r"C:\Program Files\Tesseract-OCR"
tesseract_exe = os.path.join(tesseract_dir, "tesseract.exe")
tessdata_dir = os.path.join(tesseract_dir, "tessdata")

print("Executable exists:", os.path.exists(tesseract_exe))
print("Hindi data exists:", os.path.exists(os.path.join(tessdata_dir, "hin.traineddata")))

os.environ["PATH"] = tesseract_dir + os.pathsep + os.environ["PATH"]
pymupdf.TESSDATA_PREFIX = tessdata_dir

print("Tesseract found:", shutil.which("tesseract"))

Executable exists: True
Hindi data exists: True
Tesseract found: C:\Program Files\Tesseract-OCR\tesseract.EXE

In [25]:
import pymupdf

pymupdf.TESSDATA_PREFIX = r"C:\Program Files\Tesseract-OCR\tessdata"

doc = pymupdf.open(pdf_path)
page = doc[38]  # PDF page 39: Hindi address

textpage = page.get_textpage_ocr(
    language="hin+eng",
    dpi=300,
    full=True
)

ocr_text = page.get_text(textpage=textpage)
print(ocr_text[:2000])

34.04.2024
37
माननीयअध्यक्ष: आइटमनं.
, महासचिव
|
42.58 hrs
PRESIDENT’S ADDRESS*
SECRETARY-GENERAL:
| beg to lay on the Table a copy of the President’s
Address to both Houses of Parliament assembled together on the 3* of January,
2024.
“HAART सदस्यगण,
इसनएसंसदभवनमेंयहमेरापहलासंबोधनहै।आज़ादीकेअमृतकालकीशुरुआतमेंयह
भव्यभवनबनाहै।यहांएकभारतश्रेष्ठभारतकीमहकभीहै।भारतकीसभ्यताऔरसंस्कृतिकी
चेतनाभीहै।इसमें, हमारीलोकतांत्रिकऔरसंसदीयपरंपराओंकेसम्मानकाप्रणभीहै।साथही,
24वींसदीकेनएभारतकेलिए, नईपरंपराओंकेनिर्माणकासंकल्पभीहै।मुझेपूराविश्वासहै
किइस
नएभवनमेंनीतियोंपरसार्थकसंवादहोगा।ऐसीनीतियां
जोआज़ादीकेअमृतकालमेंविकसित
भारतकानिर्माणकरेंगी।मैं
आपसभीकोअपनीशुभकामनाएंदेतीहूं।
माननीयसदस्यगण, यहहमारेसंविधानकेलागूहोनेकाभी75वां
वर्षहै।इसीकालखंडमें
आज़ादीके75 वर्षकाउत्सव, अमृतमहोत्सवभीसंपननहुआहै
।इसदौरानदेशभरमेंअनेक
कार्यक्रमहुए
| देशनेअपनेगुमनामस्वतंत्रतासेनानियों
कोयादकिया
| 75 सालबादयुवापीढ़ीने
फिरस्वतन्त्रतासंग्रामकेउसकालखंडकोजिया|
इसउत्सवकेदौरानमेरीमाटी, मेरादेशअभियानकेतहत, देशभरकेहरगाँवकीमिट्टीके
साथअमृतकलशदिललीलाएAT
| 2 लाखसेज्यादाशिला-फलकमस्थापितकिएगए।3 करोड़से
ज्यादालोगोंनेपंचप्राण
कीशपथली
| 70 हजारसेज्यादाअमृतसरोवरबने
|
2 लाखसेज्यादा
* Laid on the Table and also placed in Library, See No. LT
007/7/24.
“* Her Excellency Shrimati Droupadi Murmu, President of India, delivered the Address in Lok Sabha Chamber, Parliament
House of India (New building of Parliament) in Hindi, English Text of the Address was read by His Excellency, Shri
Jagdeep Dhankhar, Vice President of India.

In [26]:
import pymupdf

doc = pymupdf.open(pdf_path)

# PDF page 60: English version of the address
page = doc[59]

direct_text = page.get_text()

ocr_page = page.get_textpage_ocr(
    language="eng",
    dpi=300,
    full=True
)
ocr_text = page.get_text(textpage=ocr_page)

print("=== DIRECT EXTRACTION ===")
print(direct_text[:1000])

print("\n=== OCR EXTRACTION ===")
print(ocr_text[:1000])

=== DIRECT EXTRACTION ===
31.01.2024

58

Honorable Members,
This is my first address in this new Parliament building. This magnificent
building has been constructed at the beginning of “Azadi ka Amrit Kaal”. It is
imbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to
India’s civilization and culture. It also resonates with the resolve to respect our
democratic and parliamentary traditions. Moreover, it embodies the commitment
to forge new traditions for the new India of the 21st century. I am confident that
this new building will be witness to productive dialogue on policies -- policies that
will shape the development of ‘Viksit Bharat’ in the Amrit Kaal of our
independence. I extend my best wishes to all of you.
Honorable Members, this year is also the 75th year of adoption of our
Constitution. During this period, Amrit Mahotsav, the celebration of 75 years
of independence, was completed. During this period, many programmes were
organized across the country. The coun

=== OCR EXTRACTION ===
31.01.2024
58
Honorable Members,
This is my first address in this new Parliament building. This magnificent
building has been constructed at the beginning of “Azadi ka Amrit Kaal”.
It
is
imbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to
India’s civilization and culture.
It also resonates with the resolve to respect our
democratic and parliamentary traditions. Moreover,
it embodies the commitment
to forge new traditions for the new India of the 21st century.
| am confident that
this new building will be witness to productive dialogue on policies -- policies that
will
shape
the
development
of ‘Viksit
Bharat’
in
the
Amrit
Kaal
of
our
independence.
| extend my best wishes to all of you.
Honorable Members, this year is also the 75th year of adoption of our
Constitution. During
this
period, Amrit Mahotsav,
the celebration
of 75 years
of independence, was completed. During this period, many programmes were
organized
across the country. The country remembered
its

In [27]:
import pymupdf

doc = pymupdf.open(pdf_path)

for i, page in enumerate(doc):
    direct = page.get_text().strip()
    print(
        f"PDF page {i + 1:02}: "
        f"{len(direct):5} characters | "
        f"{direct[:100].replace(chr(10), ' ')}"
    )

PDF page 01:   325 characters | Seventeenth Series, Vol. XXIX  No. 1                                      Wednesday, January 31, 202
PDF page 02:   792 characters | EDITORIAL BOARD      Utpal Kumar Singh  Secretary-General  Lok Sabha    Mamta Kemwal   Joint Secreta
PDF page 03:   701 characters | 31.01.2024    1    C O N T E N T S    Seventeenth Series, Vol. XXIX, Fifteenth Session, 2024/1945 (S
PDF page 04:   875 characters | 31.01.2024    2    ALPHABETICAL LIST OF MEMBERS OF SEVENTEENTH LOK SABHA  Abdullah, Dr. Farooq (Srin
PDF page 05:   867 characters | 31.01.2024    3    Bachegowda, Shri B.N. (Chikkballapur)  Badal, Shri Sukhbir Singh (Firozpur)  Bada
PDF page 06:   863 characters | 31.01.2024    4    Bhamre, Dr. Subhash Ramrao (Dhule)  Bharat, Shri Margani (Rajahmundry)  Bhargava,
PDF page 07:   907 characters | 31.01.2024    5    Chatterjee, Shrimati Locket (Hooghly)  Chaudhary, Shri P. P. (Pali)  Chaudhary, S
PDF page 08:   845 characters | 31.01.2024    6    Darbar, Shri Chattar Singh (Dhar)  Das, Shri Pallab Lochan (Tezpur)  Dastidar,  D
PDF page 09:   887 characters | 31.01.2024    7    Gadkari, Shri Nitin Jairam (Nagpur)  Galla, Shri Jayadev (Guntur)  Gambhir, Shri
PDF page 10:   876 characters | 31.01.2024    8    Gupta, Shri Sangam Lal (Pratapgarh)  Gupta, Shri Sudheer (Mandsour)  Gurumoorthy,
PDF page 11:   867 characters | 31.01.2024    9     Jayakumar, Dr. K. (Tiruvallur)  Jigajinagi, Shri Ramesh Chandappa (Bijapur)   Jo
PDF page 12:   839 characters | 31.01.2024    10     Khaleque, Shri Abdul (Barpeta)  Khan, Shri Abu Taher (Murshidabad)  Khan, Shri
PDF page 13:   861 characters | 31.01.2024    11    Kumar, Shri Vijay (Gaya)  Kundariya, Shri Mohanbhai (Rajkot)  Kuriakose, Adv. De
PDF page 14:   878 characters | 31.01.2024    12    Mallah, Shri Kripanath (Karimganj)  Mallick, Dr. Rajashree (Jagatsinghpur)  Malo
PDF page 15:   879 characters | 31.01.2024    13    Mondal, Shri Sunil Kumar (Bardhaman Purba)  Mondal, Shrimati Pratima (Jaynagar)
PDF page 16:   827 characters | 31.01.2024    14    Oram, Shri Jual (Sundargarh)  Owaisi, Shri Asaduddin (Hyderabad)  Paarivendhar,
PDF page 17:   859 characters | 31.01.2024    15    Patel, Shri Hasmukhbhai S. (Ahmedabad East)  Patel, Shri Lalubhai B. (Daman & Di
PDF page 18:   848 characters | 31.01.2024    16    Pramanik, Shri Nisith (Coochbehar )  Prasad , Shri Chandeshwar (Jahanabad)  Pras
PDF page 19:   897 characters | 31.01.2024    17    Rao , Shri Nama Nageswara (Khammam)  Rao, Shri Soyam Bapu (Adilabad)  Rathod , S
PDF page 20:   881 characters | 31.01.2024    18    Revanna, Shri Prajwal (Hassan)  Rijiju, Shri Kiren (Arunachal West)  Rinku, Shri
PDF page 21:   913 characters | 31.01.2024    19    Sarkar,  Dr. Subhas (Bankura)  Sarkar, Shri Jagannath (Ranaghat)  Satyanarayana,
PDF page 22:   903 characters | 31.01.2024    20    Shinde, Dr. Shrikant Eknath (Kalyan)  Shrangare, Shri Sudhakar Tukaram (Latur)
PDF page 23:   824 characters | 31.01.2024    21    Singh, Shri Dushyant (Jhalawar-Baran)  Singh, Shri Ganesh (Satna)  Singh, Shri G
PDF page 24:   840 characters | 31.01.2024    22    Soni, Shri Sunil Kumar (Raipur)  Sonkar, Shri Vinod Kumar (Kaushambi)  Soren, Sh
PDF page 25:   930 characters | 31.01.2024    23    Thakur, Sadhvi Pragya Singh (Bhopal)  Thakur, Shri Anurag Singh (Hamirpur)  Thak
PDF page 26:   738 characters | 31.01.2024    24    Venkatesan, Shri S. (Madurai)  Verma, Shri Bhanu Pratap Singh (Jalaun)  Verma, S
PDF page 27:   393 characters | 31.01.2024    25    OFFICERS OF LOK SABHA    THE SPEAKER  Shri Om Birla      PANEL OF CHAIRPERSONS
PDF page 28:   924 characters | 31.01.2024    26    COUNCIL OF MINISTERS   CABINET MINISTERS  Shri Narendra Modi   The Prime Ministe
PDF page 29:  1037 characters | 31.01.2024    27    Shri Piyush Goyal   The Minister  of Commerce and  Industry; Minister of Consume
PDF page 30:   969 characters | 31.01.2024    28    Shri Gajendra Singh Shekhawat     The Minister of Jal Shakti   Shri Kiren Rijiju
PDF page 31:   804 characters | 31.01.2024    29    MINISTERS OF STATE (INDEPENDENT CHARGE)  Rao Inderjit Singh   The Minister of St
PDF page 32:  1097 characters | 31.01.2024    30    MINISTERS OF STATE  Shri Shripad Yesso Naik  The Minister of State in the Minist
PDF page 33:  1073 characters | 31.01.2024    31    Sadhvi Niranjan Jyoti  The Minister of State in the Ministry of  Consumer Affair
PDF page 34:  1180 characters | 31.01.2024    32    Shri Bhanu Pratap Singh Verma  The Minister of State in the Ministry of   Micro,
PDF page 35:   959 characters | 31.01.2024    33    Adv. Ajay Bhatt  The Minister of State in the Ministry of  Defence and Minister
PDF page 36:  1104 characters | 31.01.2024    34    Dr. R.K. Ranjan Singh  The Minister of State in the Ministry of  External Affair
PDF page 37:   455 characters | 31.01.2024    35    LOK SABHA DEBATES   ____________________________________________________________
PDF page 38:   732 characters | 31.01.2024    36    NATIONAL ANTHEM  The National Anthem was played.  ________  12.57½ hrs  OBSERVAT
PDF page 39:  1632 characters | 31.01.2024    37    माननीय अÅय±: आइटम नं. 1, महासिचव ।  12.58 hrs  PRESIDENT’S ADDRESS    SECRETARY
PDF page 40:  1795 characters | 31.01.2024    38    अमृत वािटकाओं का िनमाªण हòआ । 2 करोड़ से ºयादा पेड़-पौधे लगाए गए । 16 करोड़ से ºयाद
PDF page 41:  1810 characters | 31.01.2024    39    ºयादा भागीदारी सुिनिĲत हòई है। यह वीमेन लेड डेवलपम¤ट के मेरी सरकार के संकÐप को म
PDF page 42:  1452 characters | 31.01.2024    40    िमशु मोर देह ए देश मािटरे,   देशबासी चािल जाआÆतु िपिठरे।   देशर Öवराºय-पथे जेते
PDF page 43:  1770 characters | 31.01.2024    41    लाख 60 हज़ार तक पहòंच चुकì है। िदसंबर 2017 म¤, 98 लाख लोग GST देते थे, आज इनकì  स
PDF page 44:  1863 characters | 31.01.2024    42    माननीय सदÖयगण, मेरी सरकार, वेÐथ िøएटसª का सÌमान करती है तथा भारत के ÿाइवेट  से³ट
PDF page 45:  1855 characters | 31.01.2024    43    िडिजटल इंिडया के कारण ब§िकंग आसान हòई है और लोन देना भी सरल हòआ है। जनधन आधार  म
PDF page 46:  1837 characters | 31.01.2024    44    माननीय सदÖयगण, मेरी सरकार मानती है िक िवकिसत भारत कì भÓय इमारत 4 मज़बूत   ÖतंभŌ प
PDF page 47:  1743 characters | 31.01.2024    45    औषिध क¤ þŌ कì वजह से मरीजŌ के करीब 28 हजार करोड़ Łपए खचª होने से बचे ह§। कोरोनोरी
PDF page 48:  1861 characters | 31.01.2024    46    से देश कì लाखŌ मिहलाओं को बहòत मदद िमली है। मेरी सरकार ने मिहलाओं को पहली बार सश
PDF page 49:  1845 characters | 31.01.2024    47     मÂÖय-पालन ±ेý म¤ 38 हजार करोड़ Łपए से अिधक कì योजनाएं चलाई जा रही है, िजसके  कार
PDF page 50:  1849 characters | 31.01.2024    48    हर अनु¸छेद का संदेश भी यही है। हमारे यहां लंबे समय तक िसफª अिधकारŌ पर चचाª होती
PDF page 51:  1731 characters | 31.01.2024    49    ही, अगली िकÔत का भी लाभ उठाया। इस योजना के अिधकतर लाभाथê दिलत, िपछड़े, आिदवासी  औ
PDF page 52:  1643 characters | 31.01.2024    50    सरकार के ÿयासŌ के साथªक पåरणाम हमारे सामने ह§।जÌमू कÔमीर म¤ आज सुर±ा का वातावरण
PDF page 53:  1760 characters | 31.01.2024    51    अवसर बने ह§। PLI से इले³ůॉिन³स, फामाª, फूड ÿोसेिसंग और मेिडकल िडवाइस के से³टर म¤
PDF page 54:  1819 characters | 31.01.2024    52    ऊजाª के ±ेý म¤ भी बहòत तेजी से काम िकया जा रहा है। मेरी सरकार ने 10 नए परमाणु ऊज
PDF page 55:  1801 characters | 31.01.2024    53    भी Öवीकृत िकया है। ³वांटम कंÈयूिटंग, नए दौर कì िडिजटल ÓयवÖथा बनाएगा। इस ±ेý म¤ भ
PDF page 56:  1861 characters | 31.01.2024    54    मेरी सरकार ने देश भर म¤ तीथŎ और ऐितहािसक ÖथलŌ के िवकास पर बल िदया है। इससे अब  भ
PDF page 57:  1813 characters | 31.01.2024    55    तक ही सीिमत रखा जाता था। मेरी सरकार ने इसम¤ भी जनता कì सीधी भागीदारी सुिनिĲत कì
PDF page 58:  1203 characters | 31.01.2024    56    पĦितयŌ के िवकास के िलए एक नया मंýालय बनाया है। िवĵ ÖवाÖÃय संगठन का पहला Global
PDF page 59:   143 characters | 31.01.2024    57    लेिकन हमारी िवरासत ऐसी होनी चािहए िक तब कì पीढ़ी हम¤ याद करे।  आप सभी को बहòत-बहò
PDF page 60:  1595 characters | 31.01.2024    58    Honorable Members,  This is my first address in this new Parliament building. Th
PDF page 61:  1669 characters | 31.01.2024    59    It was during the Amrit Mahotsav that, A statue of Netaji Subhash Chandra  Bose
PDF page 62:  1777 characters | 31.01.2024    60    Honorable Members, over the past 12 months, my government introduced  several im
PDF page 63:  1335 characters | 31.01.2024    61    the national interest, for which the people of the country were waiting for deca
PDF page 64:  1666 characters | 31.01.2024    62     The achievements that are visible today are the outcome of the endeavors of las
PDF page 65:  1720 characters | 31.01.2024    63    2014-15. Whereas, till the month of December for the year 2023-24, about 12  lak
PDF page 66:  1753 characters | 31.01.2024    64    has ensured participation of the private sector in the defence sector. Our  gove
PDF page 67:  1802 characters | 31.01.2024    65    Honorable Members, another significant reform of my government is the  creation
PDF page 68:  1849 characters | 31.01.2024    66    kilometers. The length of four-lane national highways has increased 2.5 times.
PDF page 69:  1821 characters | 31.01.2024    67    been spent on this initiative. For the first time, piped water has reached about
PDF page 70:  1650 characters | 31.01.2024    68    citizens save nearly Rupees three and a half lakh crore. Jan Aushadhi Kendras  h
PDF page 71:  1736 characters | 31.01.2024    69    independence means for women. My government has made relentless efforts to  enha
PDF page 72:  1765 characters | 31.01.2024    70    Rupees 1.5 lakh crore.  In the last 10 years, farmers have  received nearly  Rup
PDF page 73:  1703 characters | 31.01.2024    71    have been given the benefit of Kisan Credit Card. In the last decade, per capita
PDF page 74:  1696 characters | 31.01.2024    72    Honorable Members, my government is focussed on human-centric  development. The
PDF page 75:  1573 characters | 31.01.2024    73    enacted to give a respectable position to transgender persons in the society and
PDF page 76:  1595 characters | 31.01.2024    74     5 places associated with Baba Saheb Ambedkar have been developed as  Panchteert
PDF page 77:  1756 characters | 31.01.2024    75    internal security are visible to us. There is a sense of security in Jammu and
PDF page 78:  1700 characters | 31.01.2024    76    of the world. Today the world believes that only India can strengthen the  globa
PDF page 79:  1792 characters | 31.01.2024    77    green energy.  In 10 years, non-fossil fuel based energy capacity has increased
PDF page 80:  1738 characters | 31.01.2024    78    Honorable Members, the quantity of important minerals in the earth is  limited.
PDF page 81:  1746 characters | 31.01.2024    79    Education Policy was framed and is being implemented rapidly. In the National  E
PDF page 82:  1673 characters | 31.01.2024    80    also advantageous. Now, North East is witnessing record tourist arrivals. Now  t
PDF page 83:  1782 characters | 31.01.2024    81    industry. In the last 10 years, India has successfully organized international s
PDF page 84:  1680 characters | 31.01.2024    82    - Middle East - Europe Corridor was announced. This corridor will further  stren
PDF page 85:  1184 characters | 31.01.2024    83    country witnessed a similar epochal  moment. After waiting for centuries, Ram  L
PDF page 86:   170 characters | 31.01.2024    84    But our legacy should be such that the future generations remember us.  Best  wi
PDF page 87:  1070 characters | 31.01.2024    85    12.58½ hrs  OBITUARY REFERENCES    माननीय अÅय±: माननीय सदÖयगण, मुझे अÂयंत दु:ख क
PDF page 88:   445 characters | 31.01.2024    86    13.00 hrs  COMMITTEE ON PRIVILEGES  7th Report    ®ी सुनील कुमार िसंह (चतरा) : म
PDF page 89:   741 characters | 31.01.2024    87            INTERNET             The Original Version of Lok Sabha proceedings is av

In [28]:
import pymupdf

pymupdf.TESSDATA_PREFIX = r"C:\Program Files\Tesseract-OCR\tessdata"

doc = pymupdf.open(pdf_path)

page_number = 48  # PDF page 49, in the Hindi address
page = doc[page_number - 1]

textpage = page.get_textpage_ocr(
    language="hin+eng",
    dpi=300,
    full=True
)

sample_text = page.get_text(textpage=textpage)
print(sample_text[:2000])

34.04.2024
46
सेदेशकीलाखोंमहिलाओंकोबहुतमददमिलीहै।मेरीसरकारनेमहिलाओंकोपहलीबारसशस्त्र
बलों
मेंपरमानेंटकमीशनदियाहै।पहलीबारसैनिकस्कूलोंऔरराष्ट्रीयरक्षाअकादमीमेंमहिला
कैडेट्सकोप्रवेशदियागयाहै।आजमहिलाएंफाइटरपायलटभीहैंऔरनौसेनाकेजहाजकोभी
पहलीबारPAS करYel Sl मुद्रायोजनाकेतहतजो46 करोड़सेज्यादालोनदिएगए
हैंउनमें
करीब34 करोड़सेज्यादालोनमहिलाओंकोमिले
हैं।इसयोजनासेलाभलेकरकरोड़ोंमहिलाओं
नेस्वरोजगारशुरुकियाहै।
माननीयसदस्यगण, मेरीसरकारआजखेतीकोअधिकलाभकारीबनानेपरबलदे
रहीहै।
हमारायहप्रयासहैकिखेतीमेंलागतकमहोऔरलाभअधिकहो
| मेरीसरकारनेपहलीबार
0
करोड़सेअधिकछोटेकिसानोंकोभीदेशकीकृषिनीतिऔरयोजनाओं
मेंप्रमुखतादीहै।पीएम-
किसानसम्माननिधिकेतहतअबतक2 लाख80 हज़ारकरोड़रुपए, किसानोंकोमिलचुके
हैं।
40
सालों
मेंकिसानोंकेलिएबैंकसेआसानलोनमें3 गुनावृद्धिकीगईहै।प्रधानमंत्रीफसलबीमा
योजनाकेतहतकिसानों
ने30 हज़ारकरोड़रुपएप्रीमियमभरा।इसकेबदले
उन्हें
डेढ़लाखकरोड़
रुपएकाFors मिलाSl पिछले
40
वर्षोंमें, लगभग
48 लाखकरोड़रुपएMSP केरूपमेंधानऔर
गेहूं
कीखेतीकरनेवालेकिसानोंकोमिले
हैं।यह2044 सेपहलेके
40 सालोंकीतुलनामेंढाईगुना
अधिकहै।पहलेतिलहनऔरदलहनफसलोंकीसरकारीखरीदनहींकेबराबरथी।पिछलेदशकमें
तिलहनऔरदलहनकीखेतीकरनेवालेकिसानोंकोMSP केरूपमेंसवालाखकरोड़रुपएमिले
al यहमेरीहीसरकारहैजिसनेपहलीबारदेशमेंकृषिनिर्यातनीतिबनाईहै।इससे
एग्रीकल्चर
URINE,
4 लाखकरोड़रुपएतकपहुंचाहै।किसानोंकोसस्तीखादमिले, इसकेलिए0 सालों
में
4
लाखकरोड़रुपएसेअधिकखर्चकिएगएहैं।मेरीसरकारनेपौनेदोलाखसे
ज्यादाप्रधानमंत्री
किसानसमृद्धिकेंद्रस्थापितकिएहैं।अभीतकलगभग8 हज़ारकिसानउत्पादकसंघ-
FPO बनाए
जाचुके
हैं।
मेरीसरकारकृषिमेंसहकारिताकोबढ़ावादेरहीहै।इसलिए, देशमेंपहलीबार
सहकारितामंत्रालयबनायागया।सहकारीक्षेत्रमें, दुनिया
कीसबसेबड़ीअनाजभंडारणयोजनाशुरू
कीगईहै।जिनगांवोंमेंसहकारीसमितियांनहीं
हैं, वहां2लाखसमितियांबनाईजारहीहैं।

In [29]:
import pymupdf
from pathlib import Path

pdf_path = Path("data/raw/Floor.pdf")
doc = pymupdf.open(pdf_path)

records = []

for page_index in range(59, 86):  # PDF pages 60–86
    page = doc[page_index]
    text = page.get_text("text").strip()

    if text:
        records.append({
            "document_id": "president_address_2024_01_31",
            "source_file": pdf_path.name,
            "pdf_page": page_index + 1,
            "language": "en",
            "extraction_method": "direct",
            "text": text
        })

print("Pages extracted:", len(records))
print("First record:")
print(records[0])

Pages extracted: 27
First record:
{'document_id': 'president_address_2024_01_31', 'source_file': 'Floor.pdf', 'pdf_page': 60, 'language': 'en', 'extraction_method': 'direct', 'text': '31.01.2024 \n \n58 \n \nHonorable Members, \nThis is my first address in this new Parliament building. This magnificent \nbuilding has been constructed at the beginning of “Azadi ka Amrit Kaal”. It is \nimbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to \nIndia’s civilization and culture. It also resonates with the resolve to respect our \ndemocratic and parliamentary traditions. Moreover, it embodies the commitment \nto forge new traditions for the new India of the 21st century. I am confident that \nthis new building will be witness to productive dialogue on policies -- policies that \nwill shape the development of ‘Viksit Bharat’ in the Amrit Kaal of our \nindependence. I extend my best wishes to all of you. \nHonorable Members, this year is also the 75th year of adoption of our \nConstitution. During this period, Amrit Mahotsav, the celebration of 75 years \nof independence, was completed. During this period, many programmes were \norganized across the country. The country remembered its unsung freedom \nfighters. After 75 years, the young generation relived that period of \nfreedom struggle. \nDuring this campaign Amrit Kalash containing soil from every village of the \ncountry were brought to Delhi under the ‘Meri Maati, Mera Desh’ campaign. Over \n2 lakh plaques were installed.  More than three crore people took the oath of the \n‘Panch Pran’.  More than 70,000 Amrit Sarovars were built. Construction of more \nthan two lakh “Amrit Vatikas” was completed. Over two crore trees were planted. \nMore than 16 crore people uploaded their selfies with the Tricolour.'}

In [30]:
import json
from pathlib import Path

output_path = Path("data/processed/president_address_en.jsonl")
output_path.parent.mkdir(parents=True, exist_ok=True)

with output_path.open("w", encoding="utf-8") as f:
    for record in records:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")

print("Saved to:", output_path.resolve())
print("Records saved:", len(records))

Saved to: C:\Users\Tony\Documents\Lok_Sabha_AI\data\processed\president_address_en.jsonl
Records saved: 27

In [31]:
with output_path.open("r", encoding="utf-8") as f:
    first_record = json.loads(f.readline())

print("PDF page:", first_record["pdf_page"])
print("Language:", first_record["language"])
print("Extraction:", first_record["extraction_method"])
print(first_record["text"][:500])

PDF page: 60
Language: en
Extraction: direct
31.01.2024

58

Honorable Members,
This is my first address in this new Parliament building. This magnificent
building has been constructed at the beginning of “Azadi ka Amrit Kaal”. It is
imbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to
India’s civilization and culture. It also resonates with the resolve to respect our
democratic and parliamentary traditions. Moreover, it embodies the commitment
to forge new traditions for the new India of the 21st centu

In [32]:
import re
def normalize_text(text):
    text = text.strip()
    text = re.sub(r"[ \t]+"," ",text)
    text = re.sub(r"\n{3,}","\n\n",text)
    return text

In [33]:
original_text = first_record["text"]
cleaned_text = normalize_text(original_text)

print("BEFORE:\n")
print(original_text[:700])

print("\nAFTER:\n")
print(cleaned_text[:700])

BEFORE:

31.01.2024

58

Honorable Members,
This is my first address in this new Parliament building. This magnificent
building has been constructed at the beginning of “Azadi ka Amrit Kaal”. It is
imbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to
India’s civilization and culture. It also resonates with the resolve to respect our
democratic and parliamentary traditions. Moreover, it embodies the commitment
to forge new traditions for the new India of the 21st century. I am confident that
this new building will be witness to productive dialogue on policies -- policies that
will shape the development of ‘Viksit Bharat’ in the Amrit Kaal of our
independence. I

AFTER:

31.01.2024

58

Honorable Members,
This is my first address in this new Parliament building. This magnificent
building has been constructed at the beginning of “Azadi ka Amrit Kaal”. It is
imbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to
India’s civilization and culture. It also resonates with the resolve to respect our
democratic and parliamentary traditions. Moreover, it embodies the commitment
to forge new traditions for the new India of the 21st century. I am confident that
this new building will be witness to productive dialogue on policies -- policies that
will shape the development of ‘Viksit Bharat’ in the Amrit Kaal of our
independence. I

In [34]:
for record in records:
    record["cleaned_text"] = normalize_text(record["text"])

print("Records processed:", len(records))
print("Original text preserved:", "text" in records[0])
print("Cleaned text available:", "cleaned_text" in records[0])

Records processed: 27
Original text preserved: True
Cleaned text available: True

In [35]:
changed_pages = [
    record for record in records
    if record["text"] != record["cleaned_text"]
]

print("Pages changed by normalization:", len(changed_pages))

for record in changed_pages[:3]:
    print("\nPDF page:", record["pdf_page"])
    print("BEFORE:", repr(record["text"][:200]))
    print("AFTER: ", repr(record["cleaned_text"][:200]))

Pages changed by normalization: 20

PDF page: 60
BEFORE: '31.01.2024 \n \n58 \n \nHonorable Members, \nThis is my first address in this new Parliament building. This magnificent \nbuilding has been constructed at the beginning of “Azadi ka Amrit Kaal”. It is \nimbu'
AFTER:  '31.01.2024 \n \n58 \n \nHonorable Members, \nThis is my first address in this new Parliament building. This magnificent \nbuilding has been constructed at the beginning of “Azadi ka Amrit Kaal”. It is \nimbu'

PDF page: 61
BEFORE: '31.01.2024 \n \n59 \n \nIt was during the Amrit Mahotsav that, A statue of Netaji Subhash Chandra \nBose was installed on “Kartavya Path”. A museum dedicated to all the Prime \nMinisters of the country was '
AFTER:  '31.01.2024 \n \n59 \n \nIt was during the Amrit Mahotsav that, A statue of Netaji Subhash Chandra \nBose was installed on “Kartavya Path”. A museum dedicated to all the Prime \nMinisters of the country was '

PDF page: 63
BEFORE: '31.01.2024 \n \n61 \n \nthe national interest, for which the people of the country were waiting for decades. \nFor centuries, there was an aspiration to construct the Ram Mandir. Today it is a \nreality. Th'
AFTER:  '31.01.2024 \n \n61 \n \nthe national interest, for which the people of the country were waiting for decades. \nFor centuries, there was an aspiration to construct the Ram Mandir. Today it is a \nreality. Th'

In [36]:
for record in changed_pages[:3]:
    print(f"\nPDF page: {record['pdf_page']}")

    print("BEFORE:")
    print(repr(record["text"][:150]))

    print("AFTER:")
    print(repr(record["cleaned_text"][:150]))

PDF page: 60
BEFORE:
'31.01.2024 \n \n58 \n \nHonorable Members, \nThis is my first address in this new Parliament building. This magnificent \nbuilding has been constructed at t'
AFTER:
'31.01.2024 \n \n58 \n \nHonorable Members, \nThis is my first address in this new Parliament building. This magnificent \nbuilding has been constructed at t'

PDF page: 61
BEFORE:
'31.01.2024 \n \n59 \n \nIt was during the Amrit Mahotsav that, A statue of Netaji Subhash Chandra \nBose was installed on “Kartavya Path”. A museum dedicat'
AFTER:
'31.01.2024 \n \n59 \n \nIt was during the Amrit Mahotsav that, A statue of Netaji Subhash Chandra \nBose was installed on “Kartavya Path”. A museum dedicat'

PDF page: 63
BEFORE:
'31.01.2024 \n \n61 \n \nthe national interest, for which the people of the country were waiting for decades. \nFor centuries, there was an aspiration to co'
AFTER:
'31.01.2024 \n \n61 \n \nthe national interest, for which the people of the country were waiting for decades. \nFor centuries, there was an aspiration to co'

In [37]:
for record in changed_pages[:3]:
    before = record["text"]
    after = record["cleaned_text"]

    print(
        f"Page {record['pdf_page']}: "
        f"{len(before)} -> {len(after)} characters; "
        f"{len(before) - len(after)} removed"
    )

Page 60: 1595 -> 1593 characters; 2 removed
Page 61: 1669 -> 1667 characters; 2 removed
Page 63: 1335 -> 1317 characters; 18 removed

In [38]:
for record in changed_pages[:3]:
    before = record["text"]
    after = record["cleaned_text"]

    print(f"\nPDF page: {record['pdf_page']}")

    # Show positions where the text differs
    for i, (old, new) in enumerate(zip(before, after)):
        if old != new:
            start = max(0, i - 40)
            end = min(len(before), i + 60)

            print("BEFORE:", repr(before[start:end]))
            print("AFTER: ", repr(after[start:end]))
            break

PDF page: 60
BEFORE: 'n. Over \n2 lakh plaques were installed.  More than three crore people took the oath of the \n‘Panch P'
AFTER:  'n. Over \n2 lakh plaques were installed. More than three crore people took the oath of the \n‘Panch Pr'

PDF page: 61
BEFORE: 'declared in the memory of “Sahibzaade”.  Birth anniversary of \nBhagwan Birsa Munda was declared as “'
AFTER:  'declared in the memory of “Sahibzaade”. Birth anniversary of \nBhagwan Birsa Munda was declared as “J'

PDF page: 63
BEFORE: 'e had said, \nिमशु मोर देह ए देश मािटरे,    \nदेशबासी चािल जाआÆतु िपिठरे।  \nदेशर Öवराºय-पथे जेते गाड़, '
AFTER:  'e had said, \nिमशु मोर देह ए देश मािटरे, \nदेशबासी चािल जाआÆतु िपिठरे। \nदेशर Öवराºय-पथे जेते गाड़, \nपूŁ'

In [39]:
import json
from pathlib import Path

output_path = Path("data/processed/president_address_en_cleaned.jsonl")
output_path.parent.mkdir(parents=True, exist_ok=True)

with output_path.open("w", encoding="utf-8") as f:
    for record in records:
        cleaned_record = {
            **record,
            "text": record["cleaned_text"]
        }
        cleaned_record.pop("cleaned_text", None)

        f.write(json.dumps(cleaned_record, ensure_ascii=False) + "\n")

print("Saved cleaned records:", len(records))
print("Output file:", output_path)

Saved cleaned records: 27
Output file: data\processed\president_address_en_cleaned.jsonl

In [40]:
with output_path.open("r", encoding="utf-8") as f:
    saved_records = [json.loads(line) for line in f if line.strip()]

print("Records loaded:", len(saved_records))
print("First record page:", saved_records[0]["pdf_page"])
print("Last record page:", saved_records[-1]["pdf_page"])
print("Text field exists:", "text" in saved_records[0])
print("Temporary field removed:", "cleaned_text" not in saved_records[0])

Records loaded: 27
First record page: 60
Last record page: 86
Text field exists: True
Temporary field removed: True

In [41]:
page_text = saved_records[0]["text"]
print(page_text)

31.01.2024

58

Honorable Members,
This is my first address in this new Parliament building. This magnificent
building has been constructed at the beginning of “Azadi ka Amrit Kaal”. It is
imbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to
India’s civilization and culture. It also resonates with the resolve to respect our
democratic and parliamentary traditions. Moreover, it embodies the commitment
to forge new traditions for the new India of the 21st century. I am confident that
this new building will be witness to productive dialogue on policies -- policies that
will shape the development of ‘Viksit Bharat’ in the Amrit Kaal of our
independence. I extend my best wishes to all of you.
Honorable Members, this year is also the 75th year of adoption of our
Constitution. During this period, Amrit Mahotsav, the celebration of 75 years
of independence, was completed. During this period, many programmes were
organized across the country. The country remembered its unsung freedom
fighters. After 75 years, the young generation relived that period of
freedom struggle.
During this campaign Amrit Kalash containing soil from every village of the
country were brought to Delhi under the ‘Meri Maati, Mera Desh’ campaign. Over
2 lakh plaques were installed. More than three crore people took the oath of the
‘Panch Pran’. More than 70,000 Amrit Sarovars were built. Construction of more
than two lakh “Amrit Vatikas” was completed. Over two crore trees were planted.
More than 16 crore people uploaded their selfies with the Tricolour.

In [42]:
sentences = re.split(r"(\.\s+)", page_text)
for sentence in sentences:
    print(sentence)

31.01.2024

58

Honorable Members,
This is my first address in this new Parliament building
.
This magnificent
building has been constructed at the beginning of “Azadi ka Amrit Kaal”
.
It is
imbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to
India’s civilization and culture
.
It also resonates with the resolve to respect our
democratic and parliamentary traditions
.
Moreover, it embodies the commitment
to forge new traditions for the new India of the 21st century
.
I am confident that
this new building will be witness to productive dialogue on policies -- policies that
will shape the development of ‘Viksit Bharat’ in the Amrit Kaal of our
independence
.
I extend my best wishes to all of you
.

Honorable Members, this year is also the 75th year of adoption of our
Constitution
.
During this period, Amrit Mahotsav, the celebration of 75 years
of independence, was completed
.
During this period, many programmes were
organized across the country
.
The country remembered its unsung freedom
fighters
.
After 75 years, the young generation relived that period of
freedom struggle
.

During this campaign Amrit Kalash containing soil from every village of the
country were brought to Delhi under the ‘Meri Maati, Mera Desh’ campaign
.
Over
2 lakh plaques were installed
.
More than three crore people took the oath of the
‘Panch Pran’
.
More than 70,000 Amrit Sarovars were built
.
Construction of more
than two lakh “Amrit Vatikas” was completed
.
Over two crore trees were planted
.

More than 16 crore people uploaded their selfies with the Tricolour.

In [43]:
print("Number of pieces:", len(sentences))

for sentence in sentences[:5]:
    print(repr(sentence))

Number of pieces: 37
'31.01.2024 \n \n58 \n \nHonorable Members, \nThis is my first address in this new Parliament building'
'. '
'This magnificent \nbuilding has been constructed at the beginning of “Azadi ka Amrit Kaal”'
'. '
'It is \nimbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to \nIndia’s civilization and culture'

In [44]:
cleaned_sentences = []
for sentence in sentences:
    s = sentence.replace("\n"," ")
    s = normalize_text(s)
    cleaned_sentences.append(s)
for sentence in cleaned_sentences:
    print(sentence)

31.01.2024 58 Honorable Members, This is my first address in this new Parliament building
.
This magnificent building has been constructed at the beginning of “Azadi ka Amrit Kaal”
.
It is imbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to India’s civilization and culture
.
It also resonates with the resolve to respect our democratic and parliamentary traditions
.
Moreover, it embodies the commitment to forge new traditions for the new India of the 21st century
.
I am confident that this new building will be witness to productive dialogue on policies -- policies that will shape the development of ‘Viksit Bharat’ in the Amrit Kaal of our independence
.
I extend my best wishes to all of you
.
Honorable Members, this year is also the 75th year of adoption of our Constitution
.
During this period, Amrit Mahotsav, the celebration of 75 years of independence, was completed
.
During this period, many programmes were organized across the country
.
The country remembered its unsung freedom fighters
.
After 75 years, the young generation relived that period of freedom struggle
.
During this campaign Amrit Kalash containing soil from every village of the country were brought to Delhi under the ‘Meri Maati, Mera Desh’ campaign
.
Over 2 lakh plaques were installed
.
More than three crore people took the oath of the ‘Panch Pran’
.
More than 70,000 Amrit Sarovars were built
.
Construction of more than two lakh “Amrit Vatikas” was completed
.
Over two crore trees were planted
.
More than 16 crore people uploaded their selfies with the Tricolour.

In [45]:
print(len(cleaned_sentences))

37

In [46]:
chunks = []
current_chunk = ""

for sentence in cleaned_sentences:
    if len(current_chunk + " " + sentence) > 500:
        chunks.append(current_chunk)
        current_chunk = sentence
    else:
        current_chunk += " " + sentence


if current_chunk:
    chunks.append(current_chunk)

In [47]:
print("Number of chunks:", len(chunks))
print("Chunk lengths:", [len(chunk) for chunk in chunks])

Number of chunks: 4
Chunk lengths: [497, 485, 496, 104]

In [48]:
for i, chunk in enumerate(chunks, start=1):
    print(f"\n--- Chunk {i} ---")
    print(chunk[:150])

--- Chunk 1 ---
 31.01.2024 58 Honorable Members, This is my first address in this new Parliament building . This magnificent building has been constructed at the beg

--- Chunk 2 ---
I am confident that this new building will be witness to productive dialogue on policies -- policies that will shape the development of ‘Viksit Bharat

--- Chunk 3 ---
The country remembered its unsung freedom fighters . After 75 years, the young generation relived that period of freedom struggle . During this campai

--- Chunk 4 ---
Over two crore trees were planted . More than 16 crore people uploaded their selfies with the Tricolour.

In [49]:
test_text = "building . This magnificent building"
print(re.sub(r"\s+([.!?])", r"\1", test_text))

building. This magnificent building

In [50]:
chunks = [
    re.sub(r"\s+([.!?])", r"\1", chunk)
    for chunk in chunks
]

print([len(chunk) for chunk in chunks])
print(chunks[0][:150])

[492, 480, 489, 103]
 31.01.2024 58 Honorable Members, This is my first address in this new Parliament building. This magnificent building has been constructed at the begi

In [51]:
print(saved_records[0].keys())
print(saved_records[0]["pdf_page"])
print(saved_records[0]["text"][:200])

dict_keys(['document_id', 'source_file', 'pdf_page', 'language', 'extraction_method', 'text'])
60
31.01.2024

58

Honorable Members,
This is my first address in this new Parliament building. This magnificent
building has been constructed at the beginning of “Azadi ka Amrit Kaal”. It is
imbu

In [52]:
parts = re.split(r"\n\s*\n", saved_records[0]["text"].strip())

for i, part in enumerate(parts):
    print(i, repr(part[:100]))

0 '31.01.2024 '
1 '58 '
2 'Honorable Members, \nThis is my first address in this new Parliament building. This magnificent \nbuil'

In [53]:
speech_text = parts[2]
print(speech_text[:150])

Honorable Members,
This is my first address in this new Parliament building. This magnificent
building has been constructed at the beginning of “Aza

In [54]:
sentences = re.split(r"(?<=\.)\s+", speech_text)
for sentence in sentences[:3]:
    print(repr(sentence))

'Honorable Members, \nThis is my first address in this new Parliament building.'
'This magnificent \nbuilding has been constructed at the beginning of “Azadi ka Amrit Kaal”.'
'It is \nimbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to \nIndia’s civilization and culture.'

In [55]:
cleaned_sentences = []
for sentence in sentences:
    cleaned_sentences.append(sentence.replace("\n"," "))
print(cleaned_sentences)

['Honorable Members,  This is my first address in this new Parliament building.', 'This magnificent  building has been constructed at the beginning of “Azadi ka Amrit Kaal”.', 'It is  imbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to  India’s civilization and culture.', 'It also resonates with the resolve to respect our  democratic and parliamentary traditions.', 'Moreover, it embodies the commitment  to forge new traditions for the new India of the 21st century.', 'I am confident that  this new building will be witness to productive dialogue on policies -- policies that  will shape the development of ‘Viksit Bharat’ in the Amrit Kaal of our  independence.', 'I extend my best wishes to all of you.', 'Honorable Members, this year is also the 75th year of adoption of our  Constitution.', 'During this period, Amrit Mahotsav, the celebration of 75 years  of independence, was completed.', 'During this period, many programmes were  organized across the country.', 'The country remembered its unsung freedom  fighters.', 'After 75 years, the young generation relived that period of  freedom struggle.', 'During this campaign Amrit Kalash containing soil from every village of the  country were brought to Delhi under the ‘Meri Maati, Mera Desh’ campaign.', 'Over  2 lakh plaques were installed.', 'More than three crore people took the oath of the  ‘Panch Pran’.', 'More than 70,000 Amrit Sarovars were built.', 'Construction of more  than two lakh “Amrit Vatikas” was completed.', 'Over two crore trees were planted.', 'More than 16 crore people uploaded their selfies with the Tricolour.']

In [56]:
cleaned_sentences = [normalize_text(s.replace("\n", " ")) for s in sentences]

In [58]:
%pip install -U langchain-text-splitters langchain-community langchain-huggingface sentence-transformers faiss-cpu

Requirement already satisfied: langchain-text-splitters in C:\Users\Tony\anaconda3\Lib\site-packages (1.1.3)
Requirement already satisfied: langchain-community in C:\Users\Tony\anaconda3\Lib\site-packages (0.4.2)
Requirement already satisfied: langchain-huggingface in C:\Users\Tony\anaconda3\Lib\site-packages (1.2.2)
Collecting langchain-huggingface
  Downloading langchain_huggingface-1.2.3-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sentence-transformers in C:\Users\Tony\anaconda3\Lib\site-packages (6.1.0)
Requirement already satisfied: faiss-cpu in C:\Users\Tony\anaconda3\Lib\site-packages (1.15.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.7 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-text-splitters) (1.6.6)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.0.19)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.14.4)
Requirement already satisfied: packaging>=23.2.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (26.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (2.13.4)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.17.1)
Requirement already satisfied: anyio in C:\Users\Tony\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (4.12.1)
Requirement already satisfied: certifi in C:\Users\Tony\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (2026.7.22)
Requirement already satisfied: httpcore==1.* in C:\Users\Tony\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (1.0.9)
Requirement already satisfied: idna in C:\Users\Tony\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (3.18)
Requirement already satisfied: h11>=0.16 in C:\Users\Tony\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in C:\Users\Tony\anaconda3\Lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (3.1.1)
Requirement already satisfied: distro>=1.7.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (1.9.0)
Requirement already satisfied: httpx2<3,>=2 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (2.13.1)
Requirement already satisfied: orjson>=3.9.14 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (2.34.2)
Requirement already satisfied: sniffio>=1.1 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (1.3.1)
Requirement already satisfied: websockets>=15.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (16.0)
Requirement already satisfied: xxhash>=3.0.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.25.0)
Requirement already satisfied: httpcore2==2.13.1 in C:\Users\Tony\anaconda3\Lib\site-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (2.13.1)
Requirement already satisfied: truststore>=0.10 in C:\Users\Tony\anaconda3\Lib\site-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.10.4)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in C:\Users\Tony\anaconda3\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\Tony\anaconda3\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (0.4.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-community) (3.14.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-community) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-community) (1.0.8)
Requirement already satisfied: numpy>=2.1.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-community) (2.4.6)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-community) (2.14.2)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-community) (2.0.51)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\Tony\anaconda3\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\Tony\anaconda3\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.2)
Requirement already satisfied: python-dotenv>=0.21.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Tony\anaconda3\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Tony\anaconda3\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-text-splitters) (2.7.0)
Requirement already satisfied: greenlet>=1 in C:\Users\Tony\anaconda3\Lib\site-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.3.2)
Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-huggingface) (1.33.0)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-huggingface) (0.23.2)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\Tony\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.6.0)
Requirement already satisfied: tqdm>=4.42.1 in C:\Users\Tony\anaconda3\Lib\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.68.2)
Requirement already satisfied: transformers<6.0.0,>=5.0.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from sentence-transformers) (5.18.0)
Requirement already satisfied: torch>=2.2 in C:\Users\Tony\anaconda3\Lib\site-packages (from sentence-transformers) (2.14.1)
Requirement already satisfied: scikit-learn>=1.1.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from sentence-transformers) (1.9.0)
Requirement already satisfied: scipy>=1.0.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from sentence-transformers) (1.18.0)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\Tony\anaconda3\Lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (2026.5.9)
Requirement already satisfied: typer in C:\Users\Tony\anaconda3\Lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.8.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.8.0)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\Tony\anaconda3\Lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.5.0)
Requirement already satisfied: setuptools>=77.0.3 in C:\Users\Tony\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\Tony\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\Tony\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in C:\Users\Tony\anaconda3\Lib\site-packages (from torch>=2.2->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in C:\Users\Tony\anaconda3\Lib\site-packages (from tqdm>=4.42.1->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from jinja2->torch>=2.2->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\Tony\anaconda3\Lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\Tony\anaconda3\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.1.2)
Downloading langchain_huggingface-1.2.3-py3-none-any.whl (34 kB)
Installing collected packages: langchain-huggingface
  Attempting uninstall: langchain-huggingface
    Found existing installation: langchain-huggingface 1.2.2
    Uninstalling langchain-huggingface-1.2.2:
      Successfully uninstalled langchain-huggingface-1.2.2
Successfully installed langchain-huggingface-1.2.3
Note: you may need to restart the kernel to use updated packages.

In [59]:
import langchain_text_splitters
import langchain_community
import langchain_huggingface
import faiss

print("RAG dependencies imported successfully.")

C:\Users\Tony\AppData\Local\Temp\ipykernel_18120\128000402.py:2: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  import langchain_community

RAG dependencies imported successfully.

In [60]:
import json
from pathlib import Path
from langchain_text_splitters import RecursiveCharacterTextSplitter

input_path = Path("data/processed/president_address_en_cleaned.jsonl")

records = []

with input_path.open("r", encoding="utf-8") as f:
    for line in f:
        records.append(json.loads(line))

print("Records loaded:", len(records))
print("First record keys:", records[0].keys())

Records loaded: 27
First record keys: dict_keys(['document_id', 'source_file', 'pdf_page', 'language', 'extraction_method', 'text'])

In [61]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size = 500,
    chunk_overlap = 50,
    separators=["\n\n", "\n", ". ", " ", ""]
)

In [63]:
from langchain_core.documents import Document
documents = []
for record in records:
    document = Document(
         page_content=record["text"],
        metadata={
            "document_id": record["document_id"],
            "source_file": record["source_file"],
            "pdf_page": record["pdf_page"],
            "language": record["language"],
            "extraction_method": record["extraction_method"]
        }
    )
    documents.append(document)
    
chunks = text_splitter.split_documents(documents)

print("Pages loaded:", len(documents))
print("Chunks created:", len(chunks))
print("\nFirst chunk metadata:", chunks[0].metadata)
print("\nFirst chunk preview:\n", chunks[0].page_content[:300])

Pages loaded: 27
Chunks created: 103

First chunk metadata: {'document_id': 'president_address_2024_01_31', 'source_file': 'Floor.pdf', 'pdf_page': 60, 'language': 'en', 'extraction_method': 'direct'}

First chunk preview:
 31.01.2024

58

Honorable Members,
This is my first address in this new Parliament building. This magnificent
building has been constructed at the beginning of “Azadi ka Amrit Kaal”. It is
imbued with the fragrance of ‘Ek Bharat Shreshtha Bharat’ and is a testimony to
India’s civilization an

In [64]:
from langchain_huggingface import HuggingFaceEmbeddings

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model loaded.")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding model loaded.

In [67]:
from langchain_community.vectorstores import FAISS

vector_store = FAISS.from_documents(
    documents=chunks,
    embedding=embedding_model
)

print("FAISS index created successfully.")
print("Chunks indexed:", vector_store.index.ntotal)

FAISS index created successfully.
Chunks indexed: 103

In [68]:
question = "What did the President say about India's development?"

retrieved_docs = vector_store.similarity_search(
    question,
    k=3
)

for i, doc in enumerate(retrieved_docs, start=1):
    print(f"\n--- Source {i} ---")
    print("PDF page:", doc.metadata["pdf_page"])
    print(doc.page_content[:500])

--- Source 1 ---
PDF page: 77
taken keeping this goal in mind.
Honorable Members, today every agency in the world is assured of India’s
rapid development. The assessments of the national and international agencies
are based on India’s policies. Record investments in infrastructure and policy
reforms are further boosting investors’ confidence. The preference of Indians for a
stable and strong government with full majority has also renewed the confidence

--- Source 2 ---
PDF page: 80
this.

My government is engaged in making India a major space power in the
world. It is a means to improve human life. Besides, this also attempts to increase
India’s share in the space economy. Major decisions have been taken to expand
India’s space programme. This has led to the formation of many new space
startups. The day is not far when India’s Gaganyaan will reach space.
Honorable Members, my government has made India one of the world’s

--- Source 3 ---
PDF page: 83
held in India. The unanimous adoption of the Delhi Declaration even in a
fractured environment is historic. India’s vision from ‘women led development’ to
environmental issues has become the basis of the declaration.
Our efforts to secure permanent membership of the African Union in the G-
20 have also been appreciated. During this conference, the development of India

In [69]:
%pip install -U langchain-ollama

Collecting langchain-ollama
  Downloading langchain_ollama-1.1.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.21 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-ollama) (1.6.6)
Collecting ollama<1.0.0,>=0.6.1 (from langchain-ollama)
  Downloading ollama-0.6.3-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (0.0.19)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (0.14.4)
Requirement already satisfied: packaging>=23.2.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (26.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (2.13.4)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (0.17.1)
Requirement already satisfied: anyio in C:\Users\Tony\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (4.12.1)
Requirement already satisfied: certifi in C:\Users\Tony\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (2026.7.22)
Requirement already satisfied: httpcore==1.* in C:\Users\Tony\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (1.0.9)
Requirement already satisfied: idna in C:\Users\Tony\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (3.18)
Requirement already satisfied: h11>=0.16 in C:\Users\Tony\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in C:\Users\Tony\anaconda3\Lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (3.1.1)
Requirement already satisfied: distro>=1.7.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (1.9.0)
Requirement already satisfied: httpx2<3,>=2 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (2.13.1)
Requirement already satisfied: orjson>=3.9.14 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (2.34.2)
Requirement already satisfied: sniffio>=1.1 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (1.3.1)
Requirement already satisfied: websockets>=15.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (16.0)
Requirement already satisfied: xxhash>=3.0.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (0.25.0)
Requirement already satisfied: httpcore2==2.13.1 in C:\Users\Tony\anaconda3\Lib\site-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (2.13.1)
Requirement already satisfied: truststore>=0.10 in C:\Users\Tony\anaconda3\Lib\site-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (0.10.4)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\Tony\anaconda3\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in C:\Users\Tony\anaconda3\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\Tony\anaconda3\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Tony\anaconda3\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Tony\anaconda3\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (2.7.0)
Downloading langchain_ollama-1.1.0-py3-none-any.whl (31 kB)
Downloading ollama-0.6.3-py3-none-any.whl (16 kB)
Installing collected packages: ollama, langchain-ollama

   ---------------------------------------- 2/2 [langchain-ollama]

Successfully installed langchain-ollama-1.1.0 ollama-0.6.3
Note: you may need to restart the kernel to use updated packages.

In [74]:
from langchain_ollama import ChatOllama

llm = ChatOllama(
    model="llama3.2:3b",
    temperature=0
)

response = llm.invoke(
    "Explain the purpose of the Indian Parliament in two sentences."
)

print(response.content)

The Indian Parliament is the supreme legislative body of India, comprising the Lok Sabha (House of the People) and the Rajya Sabha (Council of States), which together exercise the legislative powers of the country. The primary purpose of the Indian Parliament is to make, amend, and repeal laws, as well as to exercise oversight over the executive branch and ensure accountability to the people, while also representing the interests of various states and regions in the country.

In [75]:
from langchain_core.prompts import ChatPromptTemplate

question = "What did the President say about India's development?"

# 1. Retrieve relevant passages
retrieved_docs = vector_store.similarity_search(question, k=3)

# 2. Attach source-page labels to the evidence
context = "\n\n".join(
    f"[PDF p. {doc.metadata['pdf_page']}]\n{doc.page_content}"
    for doc in retrieved_docs
)

# 3. Instruct Llama to answer from the evidence
prompt = ChatPromptTemplate.from_template("""
You are a parliamentary research assistant.

Rules:
- Answer using only the supplied source passages.
- Do not add unsupported facts or assumptions.
- Cite supporting pages using the exact format [PDF p. N].
- Include citations next to the claims they support.
- If the evidence is insufficient, say so clearly.

SOURCE PASSAGES:
{context}

QUESTION:
{question}

ANSWER:
""")

messages = prompt.format_messages(
    context=context,
    question=question
)

response = llm.invoke(messages)

print(response.content)

print("\nRetrieved source pages:")
print(sorted({doc.metadata["pdf_page"] for doc in retrieved_docs}))

The President stated that "every agency in the world is assured of India's rapid development" [PDF p. 77].

Retrieved source pages:
[77, 80, 83]

In [72]:
for doc in retrieved_docs:
    print(f"PDF page: {doc.metadata['pdf_page']}")
    print(doc.page_content[:400])
    print("-" * 50)

PDF page: 77
taken keeping this goal in mind.
Honorable Members, today every agency in the world is assured of India’s
rapid development. The assessments of the national and international agencies
are based on India’s policies. Record investments in infrastructure and policy
reforms are further boosting investors’ confidence. The preference of Indians for a
stable and strong government with full majority
--------------------------------------------------
PDF page: 80
this.

My government is engaged in making India a major space power in the
world. It is a means to improve human life. Besides, this also attempts to increase
India’s share in the space economy. Major decisions have been taken to expand
India’s space programme. This has led to the formation of many new space
startups. The day is not far when India’s Gaganyaan will reach space.
Honorable Mem
--------------------------------------------------
PDF page: 83
held in India. The unanimous adoption of the Delhi Declaration even in a
fractured environment is historic. India’s vision from ‘women led development’ to
environmental issues has become the basis of the declaration.
Our efforts to secure permanent membership of the African Union in the G-
20 have also been appreciated. During this conference, the development of India
--------------------------------------------------

In [91]:
from langchain_core.prompts import ChatPromptTemplate

rag_prompt = ChatPromptTemplate.from_template("""
You are a parliamentary research assistant.

Answer the question using only the supplied source passages.
Do not add facts that are not supported by the passages.
If the evidence is insufficient, say so.
Do not write page numbers or citations in your answer.
The application will add source references separately.

SOURCE PASSAGES:
{context}

QUESTION:
{question}

ANSWER:
""")

def ask_parliament(question, k=3):
    docs = vector_store.similarity_search(question, k=k)

    context = "\n\n".join(
        f"[Retrieved PDF page {doc.metadata['pdf_page']}]\n"
        f"{doc.page_content}"
        for doc in docs
    )

    response = llm.invoke(
        rag_prompt.format_messages(
            context=context,
            question=question
        )
    )

    answer_text = response.content.strip()

    # Generate citations from actual retrieved metadata
    source_pages = sorted({
        int(doc.metadata["pdf_page"])
        for doc in docs
    })

    print("Question:", question)
    print("\nAnswer:\n", answer_text)
    print(
        "\nSources consulted:",
        ", ".join(f"[PDF p. {page}]" for page in source_pages)
    )

    return answer_text, docs

In [92]:
answer, sources = ask_parliament(
    "What did the President say about India's space programme?"
)

Question: What did the President say about India's space programme?

Answer:
 The President mentioned that major decisions have been taken to expand India's space programme, which has led to the formation of many new space startups.

Sources consulted: [PDF p. 66], [PDF p. 80], [PDF p. 84]

In [84]:
import re

def check_citations(answer, docs):
    retrieved_pages = {
        int(doc.metadata["pdf_page"])
        for doc in docs
    }

    cited_pages = {
        int(page)
        for page in re.findall(
            r"\[PDF p\.\s*(\d+)\]",
            answer
        )
    }

    invalid_pages = cited_pages - retrieved_pages

    print("Retrieved pages:", sorted(retrieved_pages))
    print("Cited pages:", sorted(cited_pages))
    print("Invalid citations:", sorted(invalid_pages))

    return len(invalid_pages) == 0

In [85]:
citation_valid = check_citations(answer, sources)
print("Citation validation passed:", citation_valid)

Retrieved pages: [66, 80, 84]
Cited pages: [64, 80]
Invalid citations: [64]
Citation validation passed: False

In [86]:
import re

def validate_rag_answer(answer, docs):
    retrieved_pages = {
        int(doc.metadata["pdf_page"])
        for doc in docs
    }

    cited_pages = {
        int(page)
        for page in re.findall(
            r"\[PDF p\.\s*(\d+)\]",
            answer
        )
    }

    invalid_pages = cited_pages - retrieved_pages

    if invalid_pages:
        print(
            "WARNING: The answer contains citations "
            "to pages that were not retrieved:",
            sorted(invalid_pages)
        )
        return False

    print("All cited pages are among the retrieved sources.")
    return True

In [87]:
validate_rag_answer(answer, sources)

WARNING: The answer contains citations to pages that were not retrieved: [64]

False

In [88]:
from pathlib import Path

index_path = Path("data/processed/faiss_president_address")

index_path.parent.mkdir(parents=True, exist_ok=True)

vector_store.save_local(str(index_path))

print("FAISS index saved to:", index_path.resolve())

FAISS index saved to: C:\Users\Tony\Documents\Lok_Sabha_AI\data\processed\faiss_president_address

In [89]:
import re

def make_citation_safe(answer, docs):
    retrieved_pages = {
        int(doc.metadata["pdf_page"])
        for doc in docs
    }

    cited_pages = {
        int(page)
        for page in re.findall(
            r"\[PDF p\.\s*(\d+)\]",
            answer
        )
    }

    invalid_pages = cited_pages - retrieved_pages

    if invalid_pages:
        evidence = "\n\n".join(
            f"[PDF p. {doc.metadata['pdf_page']}]\n"
            f"{doc.page_content}"
            for doc in docs
        )

        return (
            "The generated answer failed citation validation. "
            f"Unverified page citations: {sorted(invalid_pages)}. "
            "Please review the retrieved evidence below instead.\n\n"
            + evidence
        )

    return answer

In [90]:
safe_answer = make_citation_safe(answer, sources)
print(safe_answer)

The generated answer failed citation validation. Unverified page citations: [64]. Please review the retrieved evidence below instead.

[PDF p. 80]
this.

My government is engaged in making India a major space power in the
world. It is a means to improve human life. Besides, this also attempts to increase
India’s share in the space economy. Major decisions have been taken to expand
India’s space programme. This has led to the formation of many new space
startups. The day is not far when India’s Gaganyaan will reach space.
Honorable Members, my government has made India one of the world’s

[PDF p. 66]
31.01.2024

64

has ensured participation of the private sector in the defence sector. Our
government has opened up the space sector also for young start-ups.
Honorable Members, my government acknowledges the contribution of
wealth creators and believes in the capabilities of India’s private sector.We are
committed to creating a conducive environment for doing business in India, and
the government is consistently working towards this goal. There has been

[PDF p. 84]
31.01.2024

82

- Middle East - Europe Corridor was announced. This corridor will further
strengthen India’s maritime capability. The launch of the Global Biofuel Alliance is
also a big event. Such steps are expanding India’s role in solving
global problems.
Honorable Members, even in this era of global disputes and conflicts, my
government has firmly placed India’s interests before the world. The scope of
India’s foreign policy today has gone far beyond the constraints of the

In [93]:
from langchain_community.vectorstores import FAISS
from pathlib import Path

index_path = Path("data/processed/faiss_president_address")

loaded_vector_store = FAISS.load_local(
    str(index_path),
    embedding_model,
    allow_dangerous_deserialization=True
)

print("Reloaded chunks:", loaded_vector_store.index.ntotal)

Reloaded chunks: 103

In [94]:
question = "What did the President say about India's space programme?"

test_docs = loaded_vector_store.similarity_search(question, k=3)

for doc in test_docs:
    print(f"PDF page: {doc.metadata['pdf_page']}")
    print(doc.page_content[:250])
    print("-" * 40)

PDF page: 80
this.

My government is engaged in making India a major space power in the
world. It is a means to improve human life. Besides, this also attempts to increase
India’s share in the space economy. Major decisions have been taken to expand
India’s
----------------------------------------
PDF page: 66
31.01.2024

64

has ensured participation of the private sector in the defence sector. Our
government has opened up the space sector also for young start-ups.
Honorable Members, my government acknowledges the contribution of
wealth creators an
----------------------------------------
PDF page: 84
31.01.2024

82

- Middle East - Europe Corridor was announced. This corridor will further
strengthen India’s maritime capability. The launch of the Global Biofuel Alliance is
also a big event. Such steps are expanding India’s role in solving
g
----------------------------------------

In [95]:
from langchain_core.prompts import ChatPromptTemplate

rag_prompt = ChatPromptTemplate.from_template("""
You are a parliamentary research assistant.

Answer using only the supplied source passages.
Do not invent facts or add unsupported claims.
If the evidence is insufficient, say so.
Do not write page citations in the answer.
The application will list the retrieved source pages separately.

SOURCE PASSAGES:
{context}

QUESTION:
{question}

ANSWER:
""")

def ask_parliament(question, k=3):
    docs = loaded_vector_store.similarity_search(question, k=k)

    context = "\n\n".join(
        f"[PDF page {doc.metadata['pdf_page']}]\n{doc.page_content}"
        for doc in docs
    )

    response = llm.invoke(
        rag_prompt.format_messages(
            context=context,
            question=question
        )
    )

    source_pages = sorted({
        int(doc.metadata["pdf_page"])
        for doc in docs
    })

    print("Question:", question)
    print("\nAnswer:\n", response.content.strip())
    print(
        "\nSources:",
        ", ".join(f"PDF p. {page}" for page in source_pages)
    )

    return response.content.strip(), docs

In [96]:
answer, sources = ask_parliament(
    "What did the President say about India's space programme?"
)

Question: What did the President say about India's space programme?

Answer:
 The President mentioned that major decisions have been taken to expand India's space programme, which has led to the formation of many new space startups. They also mentioned that India's Gaganyaan will reach space, and that the government is engaged in making India a major space power in the world, which is a means to improve human life and increase India's share in the space economy.

Sources: PDF p. 66, PDF p. 80, PDF p. 84